"""Scaffolded op stubs — auto-generated by tools/new_op.py.
Each test is xfail until the op is fully implemented.
"""
from __future__ import annotations
import pytest
from lucid._C import engine as E


# ---- cube_root (scaffolded by tools/new_op.py) --------------------
@pytest.mark.xfail(reason="cube_root not yet implemented", strict=True)
@pytest.mark.parametrize("device", [E.Device.CPU, E.Device.GPU])
def test_cube_root_forward(device):
    import numpy as np
    x = np.random.randn(4, 5).astype("float32")
    t = E.TensorImpl(x, device, False)
    out = E.cube_root(t)
    assert out is not None
