#pragma once

#include <cstddef>

#include "../../api.h"

namespace lucid::backend::cpu {

LUCID_INTERNAL void im2col_1d_f32(const float* x,
                                  float* cols,
                                  int C,
                                  int L,
                                  int KL,
                                  int OL,
                                  int stride_l,
                                  int pad_l,
                                  int dilation_l);
LUCID_INTERNAL void im2col_1d_f64(const double* x,
                                  double* cols,
                                  int C,
                                  int L,
                                  int KL,
                                  int OL,
                                  int stride_l,
                                  int pad_l,
                                  int dilation_l);
LUCID_INTERNAL void col2im_1d_f32(const float* cols,
                                  float* dx,
                                  int C,
                                  int L,
                                  int KL,
                                  int OL,
                                  int stride_l,
                                  int pad_l,
                                  int dilation_l);
LUCID_INTERNAL void col2im_1d_f64(const double* cols,
                                  double* dx,
                                  int C,
                                  int L,
                                  int KL,
                                  int OL,
                                  int stride_l,
                                  int pad_l,
                                  int dilation_l);

LUCID_INTERNAL void im2col_f32(const float* x,
                               float* cols,
                               int C,
                               int H,
                               int W,
                               int KH,
                               int KW,
                               int OH,
                               int OW,
                               int stride_h,
                               int stride_w,
                               int pad_h,
                               int pad_w,
                               int dilation_h,
                               int dilation_w);
LUCID_INTERNAL void im2col_f64(const double* x,
                               double* cols,
                               int C,
                               int H,
                               int W,
                               int KH,
                               int KW,
                               int OH,
                               int OW,
                               int stride_h,
                               int stride_w,
                               int pad_h,
                               int pad_w,
                               int dilation_h,
                               int dilation_w);

LUCID_INTERNAL void col2im_f32(const float* cols,
                               float* dx,
                               int C,
                               int H,
                               int W,
                               int KH,
                               int KW,
                               int OH,
                               int OW,
                               int stride_h,
                               int stride_w,
                               int pad_h,
                               int pad_w,
                               int dilation_h,
                               int dilation_w);
LUCID_INTERNAL void col2im_f64(const double* cols,
                               double* dx,
                               int C,
                               int H,
                               int W,
                               int KH,
                               int KW,
                               int OH,
                               int OW,
                               int stride_h,
                               int stride_w,
                               int pad_h,
                               int pad_w,
                               int dilation_h,
                               int dilation_w);

LUCID_INTERNAL void im2col_3d_f32(const float* x,
                                  float* cols,
                                  int C,
                                  int D,
                                  int H,
                                  int W,
                                  int KD,
                                  int KH,
                                  int KW,
                                  int OD,
                                  int OH,
                                  int OW,
                                  int stride_d,
                                  int stride_h,
                                  int stride_w,
                                  int pad_d,
                                  int pad_h,
                                  int pad_w,
                                  int dilation_d,
                                  int dilation_h,
                                  int dilation_w);
LUCID_INTERNAL void im2col_3d_f64(const double* x,
                                  double* cols,
                                  int C,
                                  int D,
                                  int H,
                                  int W,
                                  int KD,
                                  int KH,
                                  int KW,
                                  int OD,
                                  int OH,
                                  int OW,
                                  int stride_d,
                                  int stride_h,
                                  int stride_w,
                                  int pad_d,
                                  int pad_h,
                                  int pad_w,
                                  int dilation_d,
                                  int dilation_h,
                                  int dilation_w);
LUCID_INTERNAL void col2im_3d_f32(const float* cols,
                                  float* dx,
                                  int C,
                                  int D,
                                  int H,
                                  int W,
                                  int KD,
                                  int KH,
                                  int KW,
                                  int OD,
                                  int OH,
                                  int OW,
                                  int stride_d,
                                  int stride_h,
                                  int stride_w,
                                  int pad_d,
                                  int pad_h,
                                  int pad_w,
                                  int dilation_d,
                                  int dilation_h,
                                  int dilation_w);
LUCID_INTERNAL void col2im_3d_f64(const double* cols,
                                  double* dx,
                                  int C,
                                  int D,
                                  int H,
                                  int W,
                                  int KD,
                                  int KH,
                                  int KW,
                                  int OD,
                                  int OH,
                                  int OW,
                                  int stride_d,
                                  int stride_h,
                                  int stride_w,
                                  int pad_d,
                                  int pad_h,
                                  int pad_w,
                                  int dilation_d,
                                  int dilation_h,
                                  int dilation_w);

}  // namespace lucid::backend::cpu
