#pragma once

#include <cstddef>
#include <cstdint>

#include "../../api.h"

namespace lucid::backend::cpu {

LUCID_INTERNAL void max_pool1d_forward_f32(const float* x,
                                           float* y,
                                           std::int32_t* argmax,
                                           int B,
                                           int C,
                                           int L,
                                           int KL,
                                           int OL,
                                           int stride_l,
                                           int pad_l);
LUCID_INTERNAL void max_pool1d_forward_f64(const double* x,
                                           double* y,
                                           std::int32_t* argmax,
                                           int B,
                                           int C,
                                           int L,
                                           int KL,
                                           int OL,
                                           int stride_l,
                                           int pad_l);
LUCID_INTERNAL void max_pool1d_backward_f32(
    const float* g, const std::int32_t* argmax, float* dx, int B, int C, int L, int OL);
LUCID_INTERNAL void max_pool1d_backward_f64(
    const double* g, const std::int32_t* argmax, double* dx, int B, int C, int L, int OL);
LUCID_INTERNAL void avg_pool1d_forward_f32(
    const float* x, float* y, int B, int C, int L, int KL, int OL, int stride_l, int pad_l);
LUCID_INTERNAL void avg_pool1d_forward_f64(
    const double* x, double* y, int B, int C, int L, int KL, int OL, int stride_l, int pad_l);
LUCID_INTERNAL void avg_pool1d_backward_f32(
    const float* g, float* dx, int B, int C, int L, int KL, int OL, int stride_l, int pad_l);
LUCID_INTERNAL void avg_pool1d_backward_f64(
    const double* g, double* dx, int B, int C, int L, int KL, int OL, int stride_l, int pad_l);

LUCID_INTERNAL void max_pool2d_forward_f32(const float* x,
                                           float* y,
                                           std::int32_t* argmax,
                                           int B,
                                           int C,
                                           int H,
                                           int W,
                                           int KH,
                                           int KW,
                                           int OH,
                                           int OW,
                                           int stride_h,
                                           int stride_w,
                                           int pad_h,
                                           int pad_w);
LUCID_INTERNAL void max_pool2d_forward_f64(const double* x,
                                           double* y,
                                           std::int32_t* argmax,
                                           int B,
                                           int C,
                                           int H,
                                           int W,
                                           int KH,
                                           int KW,
                                           int OH,
                                           int OW,
                                           int stride_h,
                                           int stride_w,
                                           int pad_h,
                                           int pad_w);
LUCID_INTERNAL void max_pool2d_backward_f32(const float* g,
                                            const std::int32_t* argmax,
                                            float* dx,
                                            int B,
                                            int C,
                                            int H,
                                            int W,
                                            int OH,
                                            int OW);
LUCID_INTERNAL void max_pool2d_backward_f64(const double* g,
                                            const std::int32_t* argmax,
                                            double* dx,
                                            int B,
                                            int C,
                                            int H,
                                            int W,
                                            int OH,
                                            int OW);
LUCID_INTERNAL void avg_pool2d_forward_f32(const float* x,
                                           float* y,
                                           int B,
                                           int C,
                                           int H,
                                           int W,
                                           int KH,
                                           int KW,
                                           int OH,
                                           int OW,
                                           int stride_h,
                                           int stride_w,
                                           int pad_h,
                                           int pad_w);
LUCID_INTERNAL void avg_pool2d_forward_f64(const double* x,
                                           double* y,
                                           int B,
                                           int C,
                                           int H,
                                           int W,
                                           int KH,
                                           int KW,
                                           int OH,
                                           int OW,
                                           int stride_h,
                                           int stride_w,
                                           int pad_h,
                                           int pad_w);
LUCID_INTERNAL void avg_pool2d_backward_f32(const float* g,
                                            float* dx,
                                            int B,
                                            int C,
                                            int H,
                                            int W,
                                            int KH,
                                            int KW,
                                            int OH,
                                            int OW,
                                            int stride_h,
                                            int stride_w,
                                            int pad_h,
                                            int pad_w);
LUCID_INTERNAL void avg_pool2d_backward_f64(const double* g,
                                            double* dx,
                                            int B,
                                            int C,
                                            int H,
                                            int W,
                                            int KH,
                                            int KW,
                                            int OH,
                                            int OW,
                                            int stride_h,
                                            int stride_w,
                                            int pad_h,
                                            int pad_w);

LUCID_INTERNAL void max_pool3d_forward_f32(const float* x,
                                           float* y,
                                           std::int32_t* argmax,
                                           int B,
                                           int C,
                                           int D,
                                           int H,
                                           int W,
                                           int KD,
                                           int KH,
                                           int KW,
                                           int OD,
                                           int OH,
                                           int OW,
                                           int sd,
                                           int sh,
                                           int sw,
                                           int pd,
                                           int ph,
                                           int pw);
LUCID_INTERNAL void max_pool3d_forward_f64(const double* x,
                                           double* y,
                                           std::int32_t* argmax,
                                           int B,
                                           int C,
                                           int D,
                                           int H,
                                           int W,
                                           int KD,
                                           int KH,
                                           int KW,
                                           int OD,
                                           int OH,
                                           int OW,
                                           int sd,
                                           int sh,
                                           int sw,
                                           int pd,
                                           int ph,
                                           int pw);
LUCID_INTERNAL void max_pool3d_backward_f32(const float* g,
                                            const std::int32_t* argmax,
                                            float* dx,
                                            int B,
                                            int C,
                                            int D,
                                            int H,
                                            int W,
                                            int OD,
                                            int OH,
                                            int OW);
LUCID_INTERNAL void max_pool3d_backward_f64(const double* g,
                                            const std::int32_t* argmax,
                                            double* dx,
                                            int B,
                                            int C,
                                            int D,
                                            int H,
                                            int W,
                                            int OD,
                                            int OH,
                                            int OW);
LUCID_INTERNAL void avg_pool3d_forward_f32(const float* x,
                                           float* y,
                                           int B,
                                           int C,
                                           int D,
                                           int H,
                                           int W,
                                           int KD,
                                           int KH,
                                           int KW,
                                           int OD,
                                           int OH,
                                           int OW,
                                           int sd,
                                           int sh,
                                           int sw,
                                           int pd,
                                           int ph,
                                           int pw);
LUCID_INTERNAL void avg_pool3d_forward_f64(const double* x,
                                           double* y,
                                           int B,
                                           int C,
                                           int D,
                                           int H,
                                           int W,
                                           int KD,
                                           int KH,
                                           int KW,
                                           int OD,
                                           int OH,
                                           int OW,
                                           int sd,
                                           int sh,
                                           int sw,
                                           int pd,
                                           int ph,
                                           int pw);
LUCID_INTERNAL void avg_pool3d_backward_f32(const float* g,
                                            float* dx,
                                            int B,
                                            int C,
                                            int D,
                                            int H,
                                            int W,
                                            int KD,
                                            int KH,
                                            int KW,
                                            int OD,
                                            int OH,
                                            int OW,
                                            int sd,
                                            int sh,
                                            int sw,
                                            int pd,
                                            int ph,
                                            int pw);
LUCID_INTERNAL void avg_pool3d_backward_f64(const double* g,
                                            double* dx,
                                            int B,
                                            int C,
                                            int D,
                                            int H,
                                            int W,
                                            int KD,
                                            int KH,
                                            int KW,
                                            int OD,
                                            int OH,
                                            int OW,
                                            int sd,
                                            int sh,
                                            int sw,
                                            int pd,
                                            int ph,
                                            int pw);

}  // namespace lucid::backend::cpu
