[mypy]
python_version = 3.14
ignore_missing_imports = True
allow_untyped_defs = True
allow_any_generics = True
warn_return_any = False
warn_unused_ignores = False
warn_unused_configs = True
no_implicit_reexport = True
show_error_codes = True
exclude = \.pyi$

[mypy-lucid._C.*]
ignore_missing_imports = True
ignore_errors = True

[mypy-numpy.*]
ignore_missing_imports = True
