"""VGG family — Simonyan & Zisserman, 2014."""

from lucid.models.vision.vgg._config import VGGConfig
from lucid.models.vision.vgg._model import VGG, VGGForImageClassification
from lucid.models.vision.vgg._pretrained import (
    vgg_11,
    vgg_11_bn,
    vgg_11_bn_cls,
    vgg_11_cls,
    vgg_13,
    vgg_13_bn,
    vgg_13_bn_cls,
    vgg_13_cls,
    vgg_16,
    vgg_16_bn,
    vgg_16_bn_cls,
    vgg_16_cls,
    vgg_19,
    vgg_19_bn,
    vgg_19_bn_cls,
    vgg_19_cls,
)
from lucid.models.vision.vgg._weights import (
    VGG11BNWeights,
    VGG11Weights,
    VGG13BNWeights,
    VGG13Weights,
    VGG16BNWeights,
    VGG16Weights,
    VGG19BNWeights,
    VGG19Weights,
)

__all__ = [
    "VGGConfig",
    "VGG",
    "VGGForImageClassification",
    "VGG11Weights",
    "VGG13Weights",
    "VGG16Weights",
    "VGG19Weights",
    "VGG11BNWeights",
    "VGG13BNWeights",
    "VGG16BNWeights",
    "VGG19BNWeights",
    "vgg_11",
    "vgg_11_bn",
    "vgg_11_cls",
    "vgg_11_bn_cls",
    "vgg_13",
    "vgg_13_bn",
    "vgg_13_cls",
    "vgg_13_bn_cls",
    "vgg_16",
    "vgg_16_bn",
    "vgg_16_cls",
    "vgg_16_bn_cls",
    "vgg_19",
    "vgg_19_bn",
    "vgg_19_cls",
    "vgg_19_bn_cls",
]
