// lucid/_C/autograd/Helpers.h
//
// Utility functions shared across the autograd subsystem.  Provides:
//   - Storage factory helpers (zeros, ones).
//   - In-place gradient accumulation.
//   - Element-wise arithmetic on Storage values (used by op backward passes).
//   - Comparison/masking operations needed for ReLU-family gradients.
//   - Random tensor generation (Bernoulli, uniform, normal, randint).
//   - Shape/axis normalisation helpers for reduction backward passes.
//   - Version-counter check for in-place mutation detection.
//
// All functions dispatch to the backend layer (Dispatcher) so that the same
// autograd logic works on both CPU (Accelerate / vDSP) and GPU (MLX).  The
// flat-shape wrappers below package the numel count as a 1-D Shape before
// forwarding to the Dispatcher to avoid needing the full N-D shape for
// element-wise operations.

#pragma once

#include <cstdint>
#include <memory>
#include <string_view>

#include "../core/Device.h"
#include "../core/Shape.h"
#include "../core/Storage.h"

namespace lucid {

class TensorImpl;

// Allocate a zero-filled Storage of the given shape, dtype, and device.
Storage make_zero_storage(const Shape& shape, Dtype dtype, Device device);

// Allocate a ones-filled Storage of the given shape, dtype, and device.
// Used as the default grad_seed when Engine::backward() is called without
// an explicit initial gradient.
Storage make_ones_storage(const Shape& shape, Dtype dtype, Device device);

// Reduce grad (shape grad_shape) to target_shape by summing over broadcast
// dimensions.  Used in the backward pass of binary ops that broadcast one
// operand to the other's shape.
Storage reduce_grad_to_shape(const Storage& grad,
                             const Shape& grad_shape,
                             const Shape& target_shape,
                             Dtype dtype,
                             Device device);

// Add src into dst element-wise in-place (dst += src).
//
// Handles all three Storage variants:
//   CpuStorage / CpuStorage  — hand-written typed loop (F32, F64, I32, I64).
//   GpuStorage / GpuStorage  — MLX add then rewrap the result.
//   SharedStorage variants   — obtain a CpuStorage view and delegate.
// Throws DtypeMismatch if dtype fields differ, DeviceMismatch if the
// variants belong to different device categories.
void accumulate_into(Storage& dst, const Storage& src);

// Element-wise negation: returns -s.
Storage negate_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Element-wise multiplication: returns a * b.
Storage
multiply_storages(const Storage& a, const Storage& b, std::size_t numel, Dtype dt, Device device);

// Element-wise division: returns a / b.
Storage
divide_storages(const Storage& a, const Storage& b, std::size_t numel, Dtype dt, Device device);

// Element-wise addition: returns a + b.
Storage
add_storages(const Storage& a, const Storage& b, std::size_t numel, Dtype dt, Device device);

// Element-wise subtraction: returns a - b.
Storage
subtract_storages(const Storage& a, const Storage& b, std::size_t numel, Dtype dt, Device device);

// Element-wise square: returns s * s.
Storage square_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Deep copy of s into a new Storage buffer.
Storage clone_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Element-wise natural logarithm: returns ln(s).
Storage log_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Element-wise power: returns base^expo.
Storage
pow_storage(const Storage& base, const Storage& expo, std::size_t numel, Dtype dt, Device device);

// Element-wise greater-or-equal mask: returns (a >= b) ? 1 : 0 cast to dt.
// Used in the backward pass of max/clamp-style ops.
Storage
ge_mask_storage(const Storage& a, const Storage& b, std::size_t numel, Dtype dt, Device device);

// Element-wise less-than mask: returns (a < b) ? 1 : 0 cast to dt.
Storage
lt_mask_storage(const Storage& a, const Storage& b, std::size_t numel, Dtype dt, Device device);

// Broadcast-add a scalar to every element: returns s + scalar.
Storage
add_scalar_storage(const Storage& s, double scalar, std::size_t numel, Dtype dt, Device device);

// Broadcast-multiply every element by a scalar: returns s * scalar.
Storage
mul_scalar_storage(const Storage& s, double scalar, std::size_t numel, Dtype dt, Device device);

// The following unary operations are element-wise and follow the same
// signature (s, numel, dtype, device) -> Storage.  They are generated by
// the LUCID_UNARY_HELPER macro in the .cpp file and declared individually
// here for clarity.

Storage exp_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage sqrt_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage abs_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage sign_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage reciprocal_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Trigonometric functions.
Storage sin_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage cos_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage tan_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage asin_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage acos_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage atan_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Hyperbolic functions.
Storage sinh_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage cosh_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);
Storage tanh_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Element-wise mask: returns 1 where lo <= s <= hi, else 0.
// Used in the backward pass of clamp/hardtanh to gate gradients.
Storage in_range_mask_storage(
    const Storage& s, double lo, double hi, std::size_t numel, Dtype dt, Device device);

// Element-wise mask: returns 1 where s > 0, else 0.
// Used in the ReLU backward pass.
Storage positive_mask_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Element-wise mask: returns 1 where s >= 0, else slope.
// Used in the LeakyReLU backward pass.
Storage
leaky_mask_storage(const Storage& s, double slope, std::size_t numel, Dtype dt, Device device);

// Element-wise sigmoid: returns 1 / (1 + exp(-s)).
Storage sigmoid_storage(const Storage& s, std::size_t numel, Dtype dt, Device device);

// Forward declaration needed by the bernoulli helpers below.
class Generator;

// Generate a Bernoulli dropout mask as a flat 1-D Storage with the given
// numel.  Each element is 1.0 with probability keep_prob, else 0.0.
// Supports F32 and F64.  The mask is generated on CPU then transferred to
// the target device via Dispatcher::from_cpu().
Storage bernoulli_mask_storage(
    double keep_prob, std::size_t numel, Dtype dt, Device device, Generator& gen);

// Same as bernoulli_mask_storage but uses an explicit N-D shape instead of
// a flat numel count.  The resulting Storage carries the given shape.
Storage bernoulli_mask_storage_shape(
    double keep_prob, const Shape& shape, Dtype dt, Device device, Generator& gen);

// Generate uniform random samples in [lo, hi).  F32 and F64 only.
// Samples are produced on CPU then copied to device.
Storage random_uniform_storage(
    const Shape& shape, double lo, double hi, Dtype dt, Device device, Generator& gen);

// Generate normally distributed samples with the given mean and stddev.
// Uses the Box-Muller transform.  F32 and F64 only.
Storage random_normal_storage(
    const Shape& shape, double mean, double std, Dtype dt, Device device, Generator& gen);

// Generate Bernoulli samples with probability p for value 1.  F32 and F64.
Storage
random_bernoulli_storage(const Shape& shape, double p, Dtype dt, Device device, Generator& gen);

// Generate uniform random integers in [low, high).  I32 and I64 only.
// Uses batched uint32 generation from the Generator for efficiency.
Storage random_randint_storage(const Shape& shape,
                               std::int64_t low,
                               std::int64_t high,
                               Dtype dt,
                               Device device,
                               Generator& gen);

// Normalise a list of axis indices for an ndim-dimensional tensor.
// Wraps negative indices, deduplicates, sorts, and returns a new vector.
// If axes is empty, returns all indices [0, ndim).
// Throws an index error for any axis outside [-ndim, ndim).
std::vector<int> normalize_axes(const std::vector<int>& axes, int ndim);

// Compute the output shape of a reduction over input_shape along axes.
// Reduced dimensions are removed unless keepdims is true, in which case
// they become size 1 (matching NumPy / reference semantics).
Shape reduce_output_shape(const Shape& input_shape, const std::vector<int>& axes, bool keepdims);

// Verify that the live tensor referenced by live still has the same version
// counter value as saved_version.  If the counters differ, throws
// VersionMismatch naming op_name and input_idx to identify the violating op.
// If live has expired (the TensorImpl was destroyed), the check is skipped.
class TensorImpl;
void check_version_match(const std::weak_ptr<TensorImpl>& live,
                         std::int64_t saved_version,
                         std::string_view op_name,
                         std::size_t input_idx);

// Toggle the process-wide flag that disables ``check_version_match``.
// Used by ``lucid.autograd.graph.allow_mutation_on_saved_tensors`` —
// the user opts into the unsafe contract that they will not mutate a
// saved tensor in a way that would corrupt the gradient.
bool is_mutation_on_saved_allowed();
void set_mutation_on_saved_allowed(bool v);

// Broadcast grad back to input_shape after a reduction.
//
// grad         — the gradient arriving from the consumer, with shape
//                reduce_output_shape(input_shape, axes, keepdims).
// grad_shape   — the shape of grad (must match the expected reduced shape).
// input_shape  — the shape to broadcast back to.
// axes/keepdims — must match the parameters used in the forward reduction.
//
// Throws ShapeMismatch if grad_shape does not equal the expected reduced
// shape computed from input_shape, axes, and keepdims.
Storage broadcast_back_for_reduce(const Storage& grad,
                                  const Shape& grad_shape,
                                  const Shape& input_shape,
                                  const std::vector<int>& axes,
                                  bool keepdims,
                                  Dtype dt,
                                  Device device);

}  // namespace lucid
