"""Flow Matching configuration — Lipman, Chen, Ben-Hamu, Nickel & Le, 2023.

The third step of the flow lineage.  NICE and RealNVP compose hand-designed
bijections; Neural ODE replaces them with one vector field but pays for
every training step with an ODE solve.  Flow Matching keeps the vector
field and removes the solve.
"""

from dataclasses import dataclass, field
from typing import ClassVar, Literal, override

from lucid.models._meta import model_family_meta
from lucid.models.generative._common._config import GenerativeModelConfig

# Which conditional probability path the target vector field is derived
# from.  ``"ot"`` is the paper's optimal-transport displacement path —
# straight lines at constant speed, §4.2; ``"diffusion"`` reproduces the
# variance-preserving diffusion path of prior score-based work, §4.1, and
# is included because the paper's central claim is a comparison between
# them on the same objective.
ProbabilityPath = Literal["ot", "diffusion"]

# How the divergence is obtained when scoring likelihood.  Training needs
# none of this — that is the whole point of the method — but reporting
# bits/dim does.
TraceMethod = Literal["exact", "hutchinson"]

# Distribution the Hutchinson probe is drawn from.
TraceNoise = Literal["rademacher", "gaussian"]


@model_family_meta(
    canonical_name="Flow Matching",
    citation=(
        "Lipman, Yaron, et al. "
        '"Flow Matching for Generative Modeling." International Conference '
        "on Learning Representations, 2023."
    ),
    theory=r"""
    A continuous normalizing flow is defined by a vector field: push
    samples of a simple distribution along :math:`d\mathbf{x}/dt =
    v_t(\mathbf{x})` and read off what arrives.  Training one by maximum
    likelihood, as Neural ODE does, means **solving that ODE on every
    gradient step** — the cost that kept continuous flows off the scale
    diffusion models reached.

    Flow Matching removes the solve.  Suppose a probability path
    :math:`p_t` interpolating noise and data were known, together with the
    field :math:`u_t` that generates it; then a regression would suffice,

    .. math::

        \mathcal{L}_{\mathrm{FM}}(\theta) = \mathbb{E}_{t, p_t(x)}
            \bigl\| v_t(x; \theta) - u_t(x) \bigr\|^2 .

    Neither :math:`p_t` nor :math:`u_t` is available in closed form.  The
    paper's key result — **Theorem 2** — is that they need not be.  Build
    the path *per data point*, as a mixture of conditional paths
    :math:`p_t(x \mid x_1)` each generated by a tractable
    :math:`u_t(x \mid x_1)`, and regress against the conditional field
    instead:

    .. math::

        \mathcal{L}_{\mathrm{CFM}}(\theta) =
            \mathbb{E}_{t, q(x_1), p_t(x \mid x_1)}
            \bigl\| v_t(x; \theta) - u_t(x \mid x_1) \bigr\|^2 .

    The two objectives differ by a constant, so
    :math:`\nabla_\theta \mathcal{L}_{\mathrm{FM}} =
    \nabla_\theta \mathcal{L}_{\mathrm{CFM}}`.  Training is now a
    regression against a target with a closed form: **simulation-free**.

    For Gaussian conditional paths :math:`p_t(x \mid x_1) =
    \mathcal{N}(x \mid \mu_t(x_1), \sigma_t(x_1)^2 I)`, **Theorem 3** names
    the unique generating field,

    .. math::

        u_t(x \mid x_1) = \frac{\sigma_t'(x_1)}{\sigma_t(x_1)}
            \bigl(x - \mu_t(x_1)\bigr) + \mu_t'(x_1),

    so a path is fully specified by two scalar schedules and their
    derivatives.  Two instances matter.  The **diffusion** path recovers
    the variance-preserving process score-based models use — the
    probability path they were already implicitly training, now reachable
    by regression.  The **optimal-transport** path takes the schedules
    straight,

    .. math::

        \mu_t(x_1) = t\,x_1, \qquad
        \sigma_t(x_1) = 1 - (1 - \sigma_{\min})\,t,

    which makes each conditional flow a constant-speed straight line
    between a noise sample and a data point, and collapses the regression
    target to something that does not depend on :math:`t` at all:

    .. math::

        \mathcal{L}_{\mathrm{CFM}}(\theta) =
            \mathbb{E}_{t, q(x_1), p(x_0)}
            \bigl\| v_t(\psi_t(x_0); \theta)
                - \bigl(x_1 - (1 - \sigma_{\min})\,x_0\bigr) \bigr\|^2,
        \qquad
        \psi_t(x_0) = \bigl(1 - (1 - \sigma_{\min})t\bigr) x_0 + t\,x_1 .

    Diffusion paths bend; these do not, and the particles never overshoot
    the target they are heading for.  Straighter trajectories are cheaper
    for a solver to follow, which is why sampling needs fewer function
    evaluations and why the same solver reaches a better FID.

    Time runs from noise to data: :math:`p_0 = \mathcal{N}(0, I)` and
    :math:`p_1 \approx q`.  Sampling integrates :math:`v_t` from
    :math:`t = 0` to :math:`t = 1`; likelihood integrates the same field
    backwards while accumulating :math:`-\operatorname{tr}(\partial v /
    \partial x)`, exactly as any continuous flow does.
    """,
)
@dataclass(frozen=True)
class FlowMatchingConfig(GenerativeModelConfig):
    r"""Frozen configuration for every Flow Matching variant.

    Parameters
    ----------
    sample_size : int or tuple of int, default=32
        Spatial resolution of a sample.
    in_channels : int, default=3
        Channels per sample.
    out_channels : int, default=3
        Kept equal to ``in_channels``: the field is a velocity in the same
        space as the sample, so it cannot change the dimension.
    act_fn : {"silu", "swish", "relu", "gelu"}, default="silu"
        Activation inside the velocity field.
    base_channels : int, default=128
        Width of the first U-Net stage.
    channel_mult : tuple of int, default=(1, 2, 2, 2)
        Per-stage width multipliers; the length sets the depth of the
        encoder/decoder ladder.
    num_res_blocks : int, default=2
        Residual blocks per resolution.
    attention_resolutions : tuple of int, default=(32, 16, 8)
        Spatial sizes at which self-attention is applied.
    num_head_channels : int, default=64
        Channels per attention head.  The head *count* is derived per
        block, so a stage twice as wide gets twice as many heads — the
        multi-resolution attention the architecture this borrows from
        specifies.
    dropout : float, default=0.0
        Dropout inside residual blocks.
    resnet_groups : int, default=32
        GroupNorm groups; clamped down when a stage has fewer channels.
    path : {"ot", "diffusion"}, default="ot"
        Which conditional probability path the regression target comes
        from.  Both are trained by the same objective — that equivalence
        is the paper's point — and ``"ot"`` is the one it recommends.
    sigma_min : float, default=1e-4
        Width of the Gaussian left around a data point at ``t = 1``.  The
        paper requires only that it be "sufficiently small" and publishes
        no value, so this is a choice rather than a citation; anything
        small and positive behaves the same.  At exactly zero the path
        degenerates to a pure straight line between the two samples.
    beta_min, beta_max : float, default=0.1, 20.0
        Endpoints of the linear :math:`\beta(t)` used by the diffusion
        path.  Ignored when ``path="ot"``.
    solver : str, default="dopri5"
        Method handed to :func:`lucid.diffeq.odeint` for sampling and
        likelihood — the paper's own choice.
    rtol, atol : float, default=1e-5, 1e-5
        Solver tolerances; the values the paper evaluates with.
    trace_method : {"exact", "hutchinson"} or None, default=None
        How the divergence is obtained when scoring likelihood.  ``None``
        picks by dimension.  Irrelevant to training.
    trace_noise : {"rademacher", "gaussian"}, default="rademacher"
        Probe distribution for the Hutchinson estimate.
    exact_trace_max_dim : int, default=32
        Dimension below which ``trace_method=None`` resolves to
        ``"exact"``.

    Notes
    -----
    ``in_channels`` and ``out_channels`` must agree: the field lives in
    the sample's own space.

    Examples
    --------
    >>> from lucid.models.generative.flow_matching import FlowMatchingConfig
    >>> FlowMatchingConfig().path
    'ot'
    >>> FlowMatchingConfig(sample_size=32, in_channels=3).data_dim
    3072
    """

    model_type: ClassVar[str] = "flow_matching"

    base_channels: int = 128
    channel_mult: tuple[int, ...] = field(default_factory=lambda: (1, 2, 2, 2))
    num_res_blocks: int = 2
    attention_resolutions: tuple[int, ...] = field(default_factory=lambda: (32, 16, 8))
    num_head_channels: int = 64
    dropout: float = 0.0
    resnet_groups: int = 32

    path: ProbabilityPath = "ot"
    sigma_min: float = 1e-4
    beta_min: float = 0.1
    beta_max: float = 20.0

    solver: str = "dopri5"
    rtol: float = 1e-5
    atol: float = 1e-5

    trace_method: TraceMethod | None = None
    trace_noise: TraceNoise = "rademacher"
    exact_trace_max_dim: int = 32

    @property
    def data_dim(self) -> int:
        """int: Flattened width of one sample."""
        size = self.sample_size
        height, width = size if isinstance(size, tuple) else (size, size)
        return self.in_channels * height * width

    @property
    def resolved_trace_method(self) -> TraceMethod:
        """TraceMethod: ``trace_method``, or the one implied by the dimension."""
        if self.trace_method is not None:
            return self.trace_method
        return "exact" if self.data_dim <= self.exact_trace_max_dim else "hutchinson"

    @override
    def __post_init__(self) -> None:
        super().__post_init__()
        if self.in_channels != self.out_channels:
            raise ValueError(
                f"the velocity field lives in the sample's own space, so "
                f"in_channels must equal out_channels; got {self.in_channels} "
                f"and {self.out_channels}"
            )
        if self.base_channels <= 0:
            raise ValueError(
                f"base_channels must be positive, got {self.base_channels}"
            )
        if not self.channel_mult:
            raise ValueError("channel_mult must name at least one stage")
        if any(m <= 0 for m in self.channel_mult):
            raise ValueError(
                f"channel_mult entries must be positive, got {self.channel_mult}"
            )
        if self.num_res_blocks <= 0:
            raise ValueError(
                f"num_res_blocks must be positive, got {self.num_res_blocks}"
            )
        if self.num_head_channels <= 0:
            raise ValueError(
                f"num_head_channels must be positive, got {self.num_head_channels}"
            )
        if not 0.0 <= self.dropout < 1.0:
            raise ValueError(f"dropout must lie in [0, 1), got {self.dropout}")
        if self.sigma_min < 0.0 or self.sigma_min >= 1.0:
            raise ValueError(f"sigma_min must lie in [0, 1), got {self.sigma_min}")
        if not 0.0 < self.beta_min < self.beta_max:
            raise ValueError(
                f"require 0 < beta_min < beta_max, got "
                f"min={self.beta_min}, max={self.beta_max}"
            )
        if self.rtol <= 0.0 or self.atol <= 0.0:
            raise ValueError(
                f"solver tolerances must be positive, got rtol={self.rtol}, "
                f"atol={self.atol}"
            )
        if self.exact_trace_max_dim < 1:
            raise ValueError(
                f"exact_trace_max_dim must be at least 1, got {self.exact_trace_max_dim}"
            )


__all__ = ["FlowMatchingConfig", "ProbabilityPath", "TraceMethod", "TraceNoise"]
