"""Generated by ``tools/gen_annotation_names.py`` — do not edit.

Every name a module imports only under ``if TYPE_CHECKING:``, as
``module -> ((bound name, source module, attribute or None), ...)``.
:mod:`lucid._annotation_resolver` binds them once their sources exist.
"""

NAMES: dict[str, tuple[tuple[str, str, str | None], ...]] = {
    "lucid._audit_cli": (("Sequence", "collections.abc", "Sequence"),),
    "lucid._dispatch": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._factories.converters": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("np", "numpy", None),
    ),
    "lucid._factories.creation": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._factories.random": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops._adapters": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.blas": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.complex": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.dtype": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.elementwise": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.indexing": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.predicates": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.reductions": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.shape": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._ops.composite.statistics": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._tensor._dunders": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("TensorOrScalar", "lucid._types", "TensorOrScalar"),
        ("_IndexType", "lucid._types", "_IndexType"),
    ),
    "lucid._tensor._indexing": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("TensorOrScalar", "lucid._types", "TensorOrScalar"),
        ("_IndexType", "lucid._types", "_IndexType"),
    ),
    "lucid._tensor._methods": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._tensor._repr": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._tensor._to": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid._tensor.tensor": (
        ("NpDTypeLike", "numpy.typing", "DTypeLike"),
        ("_RemovableHandle", "lucid.autograd._hooks", "RemovableHandle"),
        ("np", "numpy", None),
    ),
    "lucid._types": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("_C_engine", "lucid._C", "engine"),
        ("np", "numpy", None),
    ),
    "lucid.amp.grad_scaler": (
        ("Optimizer", "lucid.optim.optimizer", "Optimizer"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.autograd._backward": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.autograd._functional": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.autograd._hooks": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.autograd.checkpoint": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.compile": (
        ("CompiledModule", "lucid.compile._entry.module", "CompiledModule"),
        ("DiagnosisReport", "lucid.compile._debug.diagnose", "DiagnosisReport"),
        ("Module", "lucid.nn.module", "Module"),
        ("OpInfo", "lucid.compile._debug.diagnose", "OpInfo"),
        ("Tracer", "lucid._C.engine.compile", "Tracer"),
        ("compile_optimizer", "lucid.compile._optim.compiler", "compile_optimizer"),
        ("compiled_step", "lucid.compile._entry.function", "compiled_step"),
        ("diagnose", "lucid.compile._debug.diagnose", "diagnose"),
        ("fused_step", "lucid.compile._entry.fused_step", "fused_step"),
        ("make_step", "lucid.compile._entry.step", "make_step"),
    ),
    "lucid.compile._core.attention_probe": (
        ("TraceGraph", "lucid._C.engine.compile", "TraceGraph"),
    ),
    "lucid.compile._core.bn_runstats": (
        ("Module", "lucid.nn.module", "Module"),
        ("TensorImpl", "lucid._C.engine", "TensorImpl"),
    ),
    "lucid.compile._core.buffer_writes": (
        ("Tracer", "lucid._C.engine.compile", "Tracer"),
    ),
    "lucid.compile._core.fallback": (
        ("CacheKey", "lucid.compile._core.signature", "CacheKey"),
        ("Module", "lucid.nn.module", "Module"),
    ),
    "lucid.compile._core.signature": (
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.compile._debug.diagnose": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.compile._debug.trace_dump": (
        ("OpNode", "lucid._C.engine.compile", "OpNode"),
        ("TensorMeta", "lucid._C.engine.compile", "TensorMeta"),
        ("TraceGraph", "lucid._C.engine.compile", "TraceGraph"),
    ),
    "lucid.compile._entry.decode_step": (
        ("StaticCache", "lucid.utils.cache", "StaticCache"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.compile._entry.function": (("Module", "lucid.nn.module", "Module"),),
    "lucid.compile._entry.fused_step": (
        ("GradScaler", "lucid.amp.grad_scaler", "GradScaler"),
        ("Module", "lucid.nn.module", "Module"),
        ("Optimizer", "lucid.optim.optimizer", "Optimizer"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.compile._entry.module": (
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.compile._entry.segmented_step": (
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.compile._entry.step": (
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.compile._optim.compiler": (
        ("Optimizer", "lucid.optim.optimizer", "Optimizer"),
    ),
    "lucid.coreml": (
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.coreml._build": (
        ("BlobWriter", "lucid._C.engine", "BlobWriter"),
        ("MilProgram", "lucid._C.engine", "MilProgram"),
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.coreml._emit": (("Builder", "lucid.coreml._build", "Builder"),),
    "lucid.coreml._model": (
        ("Module", "lucid.nn.module", "Module"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("TensorImpl", "lucid._C.engine", "TensorImpl"),
    ),
    "lucid.coreml._spec": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.fft": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.func": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("_C_engine", "lucid._C", "engine"),
    ),
    "lucid.metal": (("lucid", "lucid", None),),
    "lucid.models._auto": (
        ("ModelConfig", "lucid.models._base", "ModelConfig"),
        ("PretrainedModel", "lucid.models._base", "PretrainedModel"),
    ),
    "lucid.models._mixins": (
        (
            "DiffusionScheduler",
            "lucid.models.generative._common._schedulers",
            "DiffusionScheduler",
        ),
        ("GenerationOutput", "lucid.models._output", "GenerationOutput"),
    ),
    "lucid.models._output": (
        ("Cache", "lucid.utils.cache", "Cache"),
        ("EncoderDecoderCache", "lucid.utils.cache", "EncoderDecoderCache"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.models._registry": (
        ("ModelConfig", "lucid.models._base", "ModelConfig"),
        ("PretrainedModel", "lucid.models._base", "PretrainedModel"),
    ),
    "lucid.models._utils._common": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.activations": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.attention": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.conv": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.dropout": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.linear": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.loss": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.metrics": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.normalization": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.functional.pooling": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.positional": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.sampling": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.functional.sparse": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.init": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.intrinsic.qat.modules": (
        ("FakeQuantize", "lucid.quantization._fake_quantize", "FakeQuantize"),
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.module": (("FunctionCtx", "lucid.autograd.function", "FunctionCtx"),),
    "lucid.nn.modules._lazy": (("Module", "lucid.nn.module", "Module"),),
    "lucid.nn.qat.conv": (
        ("FakeQuantize", "lucid.quantization._fake_quantize", "FakeQuantize"),
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.qat.linear": (
        ("FakeQuantize", "lucid.quantization._fake_quantize", "FakeQuantize"),
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.qat.sparse": (
        ("FakeQuantize", "lucid.quantization._fake_quantize", "FakeQuantize"),
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.quantized._utils": (
        ("FakeQuantize", "lucid.quantization._fake_quantize", "FakeQuantize"),
        ("ObserverBase", "lucid.quantization.observer", "ObserverBase"),
        ("Parameter", "lucid.nn.parameter", "Parameter"),
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("QDtype", "lucid.quantization._qscheme", "QDtype"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("nn", "lucid.nn", None),
    ),
    "lucid.nn.quantized.activation": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.quantized.conv": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.quantized.conv_transpose": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.quantized.dynamic.linear": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.quantized.dynamic.rnn": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.quantized.functional_module": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.quantized.intrinsic": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.quantized.linear": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.quantized.mlx_linear": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.quantized.modules": (
        ("ObserverBase", "lucid.quantization.observer", "ObserverBase"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.quantized.sparse": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.utils.clip_grad": (
        ("Parameter", "lucid.nn.parameter", "Parameter"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.nn.utils.fusion": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.nn.utils.skip_init": (("Module", "lucid.nn.module", "Module"),),
    "lucid.quantization._fake_quantize": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.quantization._functional": (
        ("QDtype", "lucid.quantization._qscheme", "QDtype"),
    ),
    "lucid.quantization._qgemm": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.quantization._quantize": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.quantization._quantize_fx": (
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("QConfigMapping", "lucid.quantization.qconfig", "QConfigMapping"),
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
        ("nn", "lucid.nn", None),
    ),
    "lucid.quantization.fuse_modules": (
        ("QConfig", "lucid.quantization.qconfig", "QConfig"),
        ("Sequence", "collections.abc", "Sequence"),
    ),
    "lucid.quantization.observer": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.signal.windows": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.special": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.utils.cache._base": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.utils.cache._dynamic": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.utils.cache._encoder_decoder": (
        ("Tensor", "lucid._tensor.tensor", "Tensor"),
    ),
    "lucid.utils.data.dataset": (("Tensor", "lucid._tensor.tensor", "Tensor"),),
    "lucid.utils.rollout._driver": (
        ("RSSM", "lucid.models.generative._common._rssm", "RSSM"),
        ("RSSMState", "lucid.models.generative._common._rssm", "RSSMState"),
    ),
    "lucid.weights._base": (
        ("Transform", "lucid.utils.transforms._base", "TransformLike"),
    ),
    "lucid.weights._loading": (
        ("Module", "lucid.nn", "Module"),
        ("Tensor", "lucid._tensor", "Tensor"),
    ),
}
