/**
 * Exception registry for the docs contract audit (``scripts/audit-docs.mjs``).
 *
 * Each entry is a DECLARATIVE WAIVER: a contract violation that is intentional
 * and justified.  A finding whose ``contract`` id and ``scope`` (slug / route)
 * match a waiver is downgraded from a hard VIOLATION to a tracked
 * "registered-exception".  Anything unmatched fails the audit.
 *
 * This is the mechanism that keeps exceptions systematic rather than ad-hoc:
 * every deviation from a component contract is either (a) declared here with a
 * rationale, or (b) a bug.  The auditor also reports DEAD waivers — entries
 * that never matched — so the registry can't rot as the site evolves.
 *
 * Scope matching:
 *   - exact slug / route        ("lucid.tensor", "/api/lucid.models")
 *   - prefix glob ending "/*"   ("lucid._C.engine/*" → that slug + descendants)
 *
 * Prefer turning an intentional deviation into a POSITIVE contract (an enforced
 * invariant) over adding a waiver here.  Example: "weights sits in its own
 * Infrastructure section" is enforced by the ``models.weights-separated``
 * contract, not waived.  Waivers are for deviations that genuinely can't be
 * expressed as a positive rule (e.g. a separate generator pipeline).
 */

export const WAIVERS = [
  {
    id: "raw-hex-image-and-meta",
    contracts: ["design.no-raw-hex"],
    scope: ["src/app/layout.tsx", "src/app/opengraph-image.tsx"],
    reason:
      "These emit colour where CSS variables/Tailwind cannot reach: the " +
      "<meta name=\"theme-color\"> value and the satori/ImageResponse OG-image " +
      "renderer both require a literal hex. The value (#0d0c15) is the " +
      "--color-lucid-bg token mirrored by hand.",
  },
  {
    id: "cpp-engine-libclang-pipeline",
    contracts: [
      "prose.no-visible-rest",
      "prose.no-rest-leak",
      "label.coverage",
      "math.no-raw-leak",
    ],
    scope: ["lucid._C.engine", "lucid._C.engine/*"],
    reason:
      "lucid._C.engine docs are generated by build-cpp-data.py (libclang) — a " +
      "separate pipeline that does not run the Griffe reST→markdown converter. " +
      "Residual NumPy-header / cross-reference-role artifacts are tracked here " +
      "and cannot be regenerated without libclang in this environment.",
  },
];

/** Does any waiver cover this (contractId, scope) finding? Returns the waiver
 *  id when matched, else null.  Mutates ``hitWaivers`` to track liveness. */
export function matchWaiver(contractId, scope, hitWaivers) {
  for (const w of WAIVERS) {
    if (!w.contracts.includes(contractId)) continue;
    const hit = w.scope.some((s) =>
      s.endsWith("/*") ? scope === s.slice(0, -2) || scope.startsWith(s.slice(0, -1)) : scope === s,
    );
    if (hit) {
      hitWaivers.add(w.id);
      return w.id;
    }
  }
  return null;
}
