// lucid/_C/coreml/MilSchema.h
//
// GENERATED by tools/gen_mil_schema.py — do not edit by hand.
//
// Core ML protobuf field numbers, read off the descriptors rather than
// transcribed. A wrong number here does not fail loudly: it produces a
// well-formed message whose reader silently ignores or misreads the
// field. tools/gen_mil_schema.py --check, run by the schema-drift test,
// is what keeps this honest across Core ML spec bumps.

#pragma once

namespace lucid::coreml::pb {

namespace Model {
constexpr int kSpecificationVersion = 1;
constexpr int kDescription = 2;
constexpr int kIsUpdatable = 10;
constexpr int kPipelineClassifier = 200;
constexpr int kPipelineRegressor = 201;
constexpr int kPipeline = 202;
constexpr int kGlmRegressor = 300;
constexpr int kSupportVectorRegressor = 301;
constexpr int kTreeEnsembleRegressor = 302;
constexpr int kNeuralNetworkRegressor = 303;
constexpr int kBayesianProbitRegressor = 304;
constexpr int kGlmClassifier = 400;
constexpr int kSupportVectorClassifier = 401;
constexpr int kTreeEnsembleClassifier = 402;
constexpr int kNeuralNetworkClassifier = 403;
constexpr int kKNearestNeighborsClassifier = 404;
constexpr int kNeuralNetwork = 500;
constexpr int kItemSimilarityRecommender = 501;
constexpr int kMlProgram = 502;
constexpr int kCustomModel = 555;
constexpr int kLinkedModel = 556;
constexpr int kClassConfidenceThresholding = 560;
constexpr int kOneHotEncoder = 600;
constexpr int kImputer = 601;
constexpr int kFeatureVectorizer = 602;
constexpr int kDictVectorizer = 603;
constexpr int kScaler = 604;
constexpr int kCategoricalMapping = 606;
constexpr int kNormalizer = 607;
constexpr int kArrayFeatureExtractor = 609;
constexpr int kNonMaximumSuppression = 610;
constexpr int kIdentity = 900;
constexpr int kTextClassifier = 2000;
constexpr int kWordTagger = 2001;
constexpr int kVisionFeaturePrint = 2002;
constexpr int kSoundAnalysisPreprocessing = 2003;
constexpr int kGazetteer = 2004;
constexpr int kWordEmbedding = 2005;
constexpr int kAudioFeaturePrint = 2006;
constexpr int kSerializedModel = 3000;
}  // namespace Model

namespace ModelDescription {
constexpr int kFunctions = 20;
constexpr int kDefaultFunctionName = 21;
constexpr int kMetadata = 100;
constexpr int kInput = 1;
constexpr int kOutput = 10;
constexpr int kState = 13;
constexpr int kPredictedFeatureName = 11;
constexpr int kPredictedProbabilitiesName = 12;
constexpr int kTrainingInput = 50;
}  // namespace ModelDescription

namespace FeatureDescription {
constexpr int kName = 1;
constexpr int kShortDescription = 2;
constexpr int kType = 3;
}  // namespace FeatureDescription

namespace FeatureType {
constexpr int kInt64Type = 1;
constexpr int kDoubleType = 2;
constexpr int kStringType = 3;
constexpr int kImageType = 4;
constexpr int kMultiArrayType = 5;
constexpr int kDictionaryType = 6;
constexpr int kSequenceType = 7;
constexpr int kStateType = 8;
constexpr int kIsOptional = 1000;
}  // namespace FeatureType

namespace ArrayFeatureType {
constexpr int kShape = 1;
constexpr int kDataType = 2;
constexpr int kEnumeratedShapes = 21;
constexpr int kShapeRange = 31;
constexpr int kIntDefaultValue = 41;
constexpr int kFloatDefaultValue = 51;
constexpr int kDoubleDefaultValue = 61;
}  // namespace ArrayFeatureType

namespace ImageFeatureType {
constexpr int kWidth = 1;
constexpr int kHeight = 2;
constexpr int kEnumeratedSizes = 21;
constexpr int kImageSizeRange = 31;
constexpr int kColorSpace = 3;
}  // namespace ImageFeatureType

namespace Metadata {
constexpr int kShortDescription = 1;
constexpr int kVersionString = 2;
constexpr int kAuthor = 3;
constexpr int kLicense = 4;
constexpr int kUserDefined = 100;
}  // namespace Metadata

namespace Program {
constexpr int kVersion = 1;
constexpr int kFunctions = 2;
constexpr int kDocString = 3;
constexpr int kAttributes = 4;
}  // namespace Program

namespace Function {
constexpr int kInputs = 1;
constexpr int kOpset = 2;
constexpr int kBlockSpecializations = 3;
constexpr int kAttributes = 4;
}  // namespace Function

namespace Block {
constexpr int kInputs = 1;
constexpr int kOutputs = 2;
constexpr int kOperations = 3;
constexpr int kAttributes = 4;
}  // namespace Block

namespace Operation {
constexpr int kType = 1;
constexpr int kInputs = 2;
constexpr int kOutputs = 3;
constexpr int kBlocks = 4;
constexpr int kAttributes = 5;
}  // namespace Operation

namespace NamedValueType {
constexpr int kName = 1;
constexpr int kType = 2;
}  // namespace NamedValueType

namespace Argument {
constexpr int kArguments = 1;
}  // namespace Argument

namespace Binding {
constexpr int kName = 1;
constexpr int kValue = 2;
}  // namespace Binding

namespace Value {
constexpr int kDocString = 1;
constexpr int kType = 2;
constexpr int kImmediateValue = 3;
constexpr int kBlobFileValue = 5;
}  // namespace Value

namespace ValueType {
constexpr int kTensorType = 1;
constexpr int kListType = 2;
constexpr int kTupleType = 3;
constexpr int kDictionaryType = 4;
constexpr int kStateType = 5;
}  // namespace ValueType

namespace TensorType {
constexpr int kDataType = 1;
constexpr int kRank = 2;
constexpr int kDimensions = 3;
constexpr int kAttributes = 4;
}  // namespace TensorType

namespace Dimension {
constexpr int kConstant = 1;
constexpr int kUnknown = 2;
}  // namespace Dimension

namespace ConstantDimension {
constexpr int kSize = 1;
}  // namespace ConstantDimension

namespace ImmediateValue {
constexpr int kTensor = 1;
constexpr int kTuple = 2;
constexpr int kList = 3;
constexpr int kDictionary = 4;
}  // namespace ImmediateValue

namespace TensorValue {
constexpr int kFloats = 1;
constexpr int kInts = 2;
constexpr int kBools = 3;
constexpr int kStrings = 4;
constexpr int kLongInts = 5;
constexpr int kDoubles = 6;
constexpr int kBytes = 7;
}  // namespace TensorValue

namespace BlobFileValue {
constexpr int kFileName = 1;
constexpr int kOffset = 2;
}  // namespace BlobFileValue

namespace ListType {
constexpr int kType = 1;
constexpr int kLength = 2;
}  // namespace ListType

namespace ListValue {
constexpr int kValues = 1;
}  // namespace ListValue

namespace DictionaryType {
constexpr int kKeyType = 1;
constexpr int kValueType = 2;
}  // namespace DictionaryType

namespace DictionaryFeatureType {
constexpr int kInt64KeyType = 1;
constexpr int kStringKeyType = 2;
}  // namespace DictionaryFeatureType

namespace StringFeatureType {
}  // namespace StringFeatureType

namespace EnumeratedShapes {
constexpr int kShapes = 1;
}  // namespace EnumeratedShapes

namespace ShapeRange {
constexpr int kSizeRanges = 1;
}  // namespace ShapeRange

namespace SizeRange {
constexpr int kLowerBound = 1;
constexpr int kUpperBound = 2;
}  // namespace SizeRange

namespace Shape {
constexpr int kShape = 1;
}  // namespace Shape

namespace ArrayFeatureType_ArrayDataType {
constexpr int kINVALID_ARRAY_DATA_TYPE = 0;
constexpr int kFLOAT32 = 65568;
constexpr int kDOUBLE = 65600;
constexpr int kINT32 = 131104;
constexpr int kINT8 = 131080;
constexpr int kFLOAT16 = 65552;
}  // namespace ArrayFeatureType_ArrayDataType

namespace ImageFeatureType_ColorSpace {
constexpr int kINVALID_COLOR_SPACE = 0;
constexpr int kGRAYSCALE = 10;
constexpr int kRGB = 20;
constexpr int kBGR = 30;
constexpr int kGRAYSCALE_FLOAT16 = 40;
}  // namespace ImageFeatureType_ColorSpace

namespace DataType {
constexpr int kUNUSED_TYPE = 0;
constexpr int kBOOL = 1;
constexpr int kSTRING = 2;
constexpr int kFLOAT8E4M3FN = 40;
constexpr int kFLOAT8E5M2 = 41;
constexpr int kFLOAT16 = 10;
constexpr int kFLOAT32 = 11;
constexpr int kFLOAT64 = 12;
constexpr int kBFLOAT16 = 13;
constexpr int kINT8 = 21;
constexpr int kINT16 = 22;
constexpr int kINT32 = 23;
constexpr int kINT64 = 24;
constexpr int kINT4 = 25;
constexpr int kUINT8 = 31;
constexpr int kUINT16 = 32;
constexpr int kUINT32 = 33;
constexpr int kUINT64 = 34;
constexpr int kUINT4 = 35;
constexpr int kUINT2 = 36;
constexpr int kUINT1 = 37;
constexpr int kUINT6 = 38;
constexpr int kUINT3 = 39;
}  // namespace DataType

}  // namespace lucid::coreml::pb
