"""lucid.nn — neural-network layers, containers and parameter state.

The stateful half of the network API.  ``Module`` owns parameters, buffers,
submodules and the hook machinery; ``Parameter`` marks a tensor as trainable
state that ``Module.parameters()`` collects and an optimizer steps.  176 names
are exported here — layers, containers, losses and the subpackages below.

Layers are deliberately thin: each holds its ``Parameter``s and delegates the
computation to the matching ``lucid.nn.functional`` entry point, so a layer
and its functional form are one implementation and one autograd path rather
than two that can drift apart.

Subpackages: ``functional`` (stateless ops), ``init`` (initialisation
schemes), ``utils`` (gradient clipping, spectral norm, pruning, packed
sequences), ``modules`` (the layer implementations re-exported here), and
``quantized`` / ``qat`` / ``intrinsic`` for the quantization stack.

Namespace discipline: ``Module``, ``Parameter`` and every layer live here and
never leak into the ``lucid`` top level — ``lucid.Linear`` does not exist by
design, so there is exactly one path to each name.
"""

from lucid.nn.module import Module, UninitializedParameterWarning
from lucid.nn.parameter import Parameter, UninitializedParameter
from lucid.nn.hooks import (
    RemovableHandle,
    register_module_full_backward_hook,
    register_module_full_backward_pre_hook,
    register_module_forward_hook,
    register_module_forward_pre_hook,
    register_module_load_state_dict_pre_hook,
    register_module_load_state_dict_post_hook,
)
from lucid.nn import functional
from lucid.nn import init
from lucid.nn import utils
from lucid.nn.modules import (
    Linear,
    NoisyLinear,
    Identity,
    Bilinear,
    LazyLinear,
    FusedLinear,
    Conv1d,
    Conv2d,
    Conv3d,
    ConvTranspose1d,
    ConvTranspose2d,
    ConvTranspose3d,
    LazyConv1d,
    LazyConv2d,
    LazyConv3d,
    LazyConvTranspose1d,
    LazyConvTranspose2d,
    LazyConvTranspose3d,
    ReLU,
    LeakyReLU,
    ELU,
    CELU,
    SELU,
    GELU,
    SiLU,
    Mish,
    Softplus,
    Hardswish,
    Hardsigmoid,
    Sigmoid,
    Tanh,
    Softmax,
    Softmax2d,
    LogSoftmax,
    RReLU,
    CosineSimilarity,
    PairwiseDistance,
    ReLU6,
    PReLU,
    Threshold,
    Hardtanh,
    LogSigmoid,
    Softsign,
    Softmin,
    GLU,
    Hardshrink,
    Tanhshrink,
    Softshrink,
    LayerNorm,
    RMSNorm,
    GroupNorm,
    BatchNorm1d,
    BatchNorm2d,
    BatchNorm3d,
    InstanceNorm1d,
    InstanceNorm2d,
    InstanceNorm3d,
    LocalResponseNorm,
    LazyBatchNorm1d,
    LazyBatchNorm2d,
    LazyBatchNorm3d,
    LazyInstanceNorm1d,
    LazyInstanceNorm2d,
    LazyInstanceNorm3d,
    MaxPool1d,
    MaxPool2d,
    MaxPool3d,
    AvgPool1d,
    AvgPool2d,
    AvgPool3d,
    AdaptiveAvgPool1d,
    AdaptiveAvgPool2d,
    AdaptiveAvgPool3d,
    AdaptiveMaxPool2d,
    AdaptiveMaxPool1d,
    AdaptiveMaxPool3d,
    LPPool1d,
    LPPool2d,
    LPPool3d,
    MaxUnpool1d,
    MaxUnpool2d,
    MaxUnpool3d,
    FractionalMaxPool2d,
    FractionalMaxPool3d,
    Dropout,
    Dropout1d,
    Dropout2d,
    Dropout3d,
    AlphaDropout,
    FeatureAlphaDropout,
    Embedding,
    EmbeddingBag,
    VectorQuantizer,
    VectorQuantizerOutput,
    RotaryEmbedding,
    SinusoidalEmbedding,
    SinusoidalEmbedding2D,
    TimestepEmbedding,
    GroupedQueryAttention,
    MultiheadAttention,
    MultiQueryAttention,
    LSTM,
    GRU,
    RNN,
    LSTMCell,
    GRUCell,
    RNNCell,
    MSELoss,
    L1Loss,
    CrossEntropyLoss,
    NLLLoss,
    BCELoss,
    BCEWithLogitsLoss,
    HuberLoss,
    SmoothL1Loss,
    KLDivLoss,
    TripletMarginLoss,
    TripletMarginWithDistanceLoss,
    CosineEmbeddingLoss,
    MarginRankingLoss,
    HingeEmbeddingLoss,
    PoissonNLLLoss,
    GaussianNLLLoss,
    CTCLoss,
    MultiMarginLoss,
    MultilabelMarginLoss,
    MultiLabelMarginLoss,
    SoftMarginLoss,
    MultiLabelSoftMarginLoss,
    Sequential,
    ModuleList,
    ModuleDict,
    ParameterList,
    ParameterDict,
    Flatten,
    Unflatten,
    Unfold,
    Fold,
    ConstantPad1d,
    ConstantPad2d,
    ConstantPad3d,
    ZeroPad1d,
    ZeroPad2d,
    ZeroPad3d,
    ReflectionPad1d,
    ReflectionPad2d,
    ReflectionPad3d,
    ReplicationPad1d,
    ReplicationPad2d,
    ReplicationPad3d,
    CircularPad1d,
    CircularPad2d,
    CircularPad3d,
    Upsample,
    UpsamplingNearest2d,
    UpsamplingBilinear2d,
    PixelShuffle,
    PixelUnshuffle,
    ChannelShuffle,
    TransformerEncoderLayer,
    TransformerEncoder,
    TransformerDecoderLayer,
    TransformerDecoder,
    Transformer,
)

__all__ = [
    "Module",
    "UninitializedParameterWarning",
    "Parameter",
    "UninitializedParameter",
    "RemovableHandle",
    "register_module_full_backward_hook",
    "register_module_full_backward_pre_hook",
    "register_module_forward_hook",
    "register_module_forward_pre_hook",
    "register_module_load_state_dict_pre_hook",
    "register_module_load_state_dict_post_hook",
    "functional",
    "init",
    "utils",
    "Linear",
    "NoisyLinear",
    "Identity",
    "Bilinear",
    "LazyLinear",
    "FusedLinear",
    "Conv1d",
    "Conv2d",
    "Conv3d",
    "ConvTranspose1d",
    "ConvTranspose2d",
    "ConvTranspose3d",
    "LazyConv1d",
    "LazyConv2d",
    "LazyConv3d",
    "LazyConvTranspose1d",
    "LazyConvTranspose2d",
    "LazyConvTranspose3d",
    "ReLU",
    "LeakyReLU",
    "ELU",
    "CELU",
    "SELU",
    "GELU",
    "SiLU",
    "Mish",
    "Softplus",
    "Hardswish",
    "Hardsigmoid",
    "Sigmoid",
    "Tanh",
    "Softmax",
    "Softmax2d",
    "RReLU",
    "CosineSimilarity",
    "PairwiseDistance",
    "LogSoftmax",
    "ReLU6",
    "PReLU",
    "Threshold",
    "Hardtanh",
    "LogSigmoid",
    "Softsign",
    "Softmin",
    "GLU",
    "Hardshrink",
    "Tanhshrink",
    "Softshrink",
    "LayerNorm",
    "RMSNorm",
    "GroupNorm",
    "BatchNorm1d",
    "BatchNorm2d",
    "BatchNorm3d",
    "InstanceNorm1d",
    "InstanceNorm2d",
    "InstanceNorm3d",
    "LocalResponseNorm",
    "LazyBatchNorm1d",
    "LazyBatchNorm2d",
    "LazyBatchNorm3d",
    "LazyInstanceNorm1d",
    "LazyInstanceNorm2d",
    "LazyInstanceNorm3d",
    "MaxPool1d",
    "MaxPool2d",
    "MaxPool3d",
    "AvgPool1d",
    "AvgPool2d",
    "AvgPool3d",
    "AdaptiveAvgPool1d",
    "AdaptiveAvgPool2d",
    "AdaptiveAvgPool3d",
    "AdaptiveMaxPool2d",
    "AdaptiveMaxPool1d",
    "AdaptiveMaxPool3d",
    "LPPool1d",
    "LPPool2d",
    "LPPool3d",
    "MaxUnpool1d",
    "MaxUnpool2d",
    "MaxUnpool3d",
    "FractionalMaxPool2d",
    "FractionalMaxPool3d",
    "Dropout",
    "Dropout1d",
    "Dropout2d",
    "Dropout3d",
    "AlphaDropout",
    "FeatureAlphaDropout",
    "Embedding",
    "EmbeddingBag",
    "VectorQuantizer",
    "VectorQuantizerOutput",
    "RotaryEmbedding",
    "SinusoidalEmbedding",
    "SinusoidalEmbedding2D",
    "TimestepEmbedding",
    "MultiheadAttention",
    "GroupedQueryAttention",
    "MultiQueryAttention",
    "LSTM",
    "GRU",
    "RNN",
    "LSTMCell",
    "GRUCell",
    "RNNCell",
    "MSELoss",
    "L1Loss",
    "CrossEntropyLoss",
    "NLLLoss",
    "BCELoss",
    "BCEWithLogitsLoss",
    "HuberLoss",
    "SmoothL1Loss",
    "KLDivLoss",
    "TripletMarginLoss",
    "TripletMarginWithDistanceLoss",
    "CosineEmbeddingLoss",
    "MarginRankingLoss",
    "HingeEmbeddingLoss",
    "PoissonNLLLoss",
    "GaussianNLLLoss",
    "CTCLoss",
    "MultiMarginLoss",
    "MultilabelMarginLoss",
    "MultiLabelMarginLoss",
    "SoftMarginLoss",
    "MultiLabelSoftMarginLoss",
    "Sequential",
    "ModuleList",
    "ModuleDict",
    "ParameterList",
    "ParameterDict",
    "Flatten",
    "Unflatten",
    "Unfold",
    "Fold",
    "ConstantPad1d",
    "ConstantPad2d",
    "ConstantPad3d",
    "ZeroPad1d",
    "ZeroPad2d",
    "ZeroPad3d",
    "ReflectionPad1d",
    "ReflectionPad2d",
    "ReflectionPad3d",
    "ReplicationPad1d",
    "ReplicationPad2d",
    "ReplicationPad3d",
    "CircularPad1d",
    "CircularPad2d",
    "CircularPad3d",
    "Upsample",
    "UpsamplingNearest2d",
    "UpsamplingBilinear2d",
    "PixelShuffle",
    "PixelUnshuffle",
    "ChannelShuffle",
    "TransformerEncoderLayer",
    "TransformerEncoder",
    "TransformerDecoderLayer",
    "TransformerDecoder",
    "Transformer",
    "quantized",
    "qat",
    "intrinsic",
]


def __getattr__(name: str) -> object:
    """Lazily import the quantization module namespaces on first access.

    ``quantized`` / ``qat`` / ``intrinsic`` are deferred so that importing
    ``lucid.nn`` never eagerly pulls in ``lucid.quantization`` (whose
    observers import ``lucid.nn`` back).  Loading them only on first access
    guarantees both packages are fully initialised, breaking the cycle.
    """
    if name in ("quantized", "qat", "intrinsic"):
        import importlib

        mod = importlib.import_module(f"lucid.nn.{name}")
        globals()[name] = mod
        return mod
    raise AttributeError(f"module 'lucid.nn' has no attribute {name!r}")
