"""Generate ``lucid/_C/coreml/MilSchema.h`` from Core ML's protobuf descriptors.

Lucid writes ``.mlpackage`` files itself — no protobuf library, no
coremltools at runtime (H4). Writing protobuf by hand is easy; the wire
format is tags and varints. Getting the *field numbers* right by hand is
where such a writer actually breaks, and it breaks silently: a wrong
number produces a well-formed message that the reader either ignores or
misreads.

So they are not written by hand. This reads the numbers off the
descriptors coremltools ships and emits a header of constants, which is
committed. The engine never imports this; it compiles against the
generated header. ``lucid/test/unit/coreml/test_schema_drift.py`` re-runs
the extraction when coremltools is installed and fails if the committed
header no longer matches, so a Core ML spec bump cannot rot the writer
unnoticed.

Usage
-----
::

    python tools/gen_mil_schema.py            # rewrite the header
    python tools/gen_mil_schema.py --check    # exit 1 if it would change
"""

from __future__ import annotations  # tooling only — outside lucid/ (H1 OK)

import argparse
import sys
from pathlib import Path
from typing import Any

HEADER_PATH = Path(__file__).resolve().parent.parent / "lucid/_C/coreml/MilSchema.h"

# The messages an ``mlProgram`` package actually needs.  Everything else in
# Model.proto describes model types Lucid does not emit (neural networks,
# tree ensembles, pipelines...), and leaving them out keeps the generated
# header reviewable.
MESSAGES = (
    "Model",
    "ModelDescription",
    "FeatureDescription",
    "FeatureType",
    "ArrayFeatureType",
    "ImageFeatureType",
    "Metadata",
    "Program",
    "Function",
    "Block",
    "Operation",
    "NamedValueType",
    "Argument",
    "Binding",
    "Value",
    "ValueType",
    "TensorType",
    "Dimension",
    "ConstantDimension",
    "ImmediateValue",
    "TensorValue",
    "BlobFileValue",
    "ListType",
    "ListValue",
    "DictionaryType",
    "DictionaryFeatureType",
    "StringFeatureType",
    "EnumeratedShapes",
    "ShapeRange",
    "SizeRange",
    "StateType",
    "StateFeatureType",
    "Shape",
)

# Enums whose values end up in the emitted bytes.
ENUMS = (
    ("ArrayFeatureType", "ArrayDataType"),
    ("ImageFeatureType", "ColorSpace"),
    ("DataType", None),
)


def _constant_name(name: str) -> str:
    """Field name to C++ constant suffix.

    These protos mix conventions — ``specificationVersion`` next to
    ``block_specializations`` — so both have to land on the same
    PascalCase shape.
    """
    return "".join(part[:1].upper() + part[1:] for part in name.split("_") if part)


def _collect() -> (
    tuple[dict[str, list[tuple[str, int]]], dict[str, list[tuple[str, int]]]]
):
    from coremltools.proto import MIL_pb2, Model_pb2

    pools: list[Any] = [Model_pb2, MIL_pb2]

    def find_message(name: str) -> Any:
        # Some of these are nested (``Argument.Binding``,
        # ``Dimension.ConstantDimension``), so a top-level lookup is not
        # enough; search the nested types too.
        for pool in pools:
            got = getattr(pool, name, None)
            if got is not None and hasattr(got, "DESCRIPTOR"):
                return got.DESCRIPTOR
        for pool in pools:
            for top in vars(pool).values():
                desc = getattr(top, "DESCRIPTOR", None)
                if desc is None or not hasattr(desc, "nested_types"):
                    continue
                for nested in desc.nested_types:
                    if nested.name == name:
                        return nested
        raise KeyError(f"gen_mil_schema: no message named {name!r}")

    fields: dict[str, list[tuple[str, int]]] = {}
    for name in MESSAGES:
        desc = find_message(name)
        fields[name] = [(f.name, f.number) for f in desc.fields]

    enums: dict[str, list[tuple[str, int]]] = {}
    for owner, enum_name in ENUMS:
        if enum_name is None:
            for pool in pools:
                et = getattr(pool, owner, None)
                if et is not None and hasattr(et, "DESCRIPTOR"):
                    desc = et.DESCRIPTOR
                    enums[owner] = [(v.name, v.number) for v in desc.values]
                    break
        else:
            desc = find_message(owner).enum_types_by_name[enum_name]
            enums[f"{owner}_{enum_name}"] = [(v.name, v.number) for v in desc.values]
    return fields, enums


def render(
    fields: dict[str, list[tuple[str, int]]], enums: dict[str, list[tuple[str, int]]]
) -> str:
    out: list[str] = []
    out.append("// lucid/_C/coreml/MilSchema.h")
    out.append("//")
    out.append("// GENERATED by tools/gen_mil_schema.py — do not edit by hand.")
    out.append("//")
    out.append(
        "// Core ML protobuf field numbers, read off the descriptors rather than"
    )
    out.append(
        "// transcribed. A wrong number here does not fail loudly: it produces a"
    )
    out.append("// well-formed message whose reader silently ignores or misreads the")
    out.append(
        "// field. tools/gen_mil_schema.py --check, run by the schema-drift test,"
    )
    out.append("// is what keeps this honest across Core ML spec bumps.")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append("namespace lucid::coreml::pb {")
    for message in MESSAGES:
        out.append("")
        out.append(f"namespace {message} {{")
        for fname, number in fields[message]:
            out.append(f"constexpr int k{_constant_name(fname)} = {number};")
        out.append(f"}}  // namespace {message}")
    for enum_name, values in enums.items():
        out.append("")
        out.append(f"namespace {enum_name} {{")
        for vname, number in values:
            out.append(f"constexpr int k{vname} = {number};")
        out.append(f"}}  // namespace {enum_name}")
    out.append("")
    out.append("}  // namespace lucid::coreml::pb")
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python tools/gen_mil_schema.py")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 if the committed header is out of date.",
    )
    args = parser.parse_args(argv)

    fields, enums = _collect()
    rendered = render(fields, enums)

    if args.check:
        current = HEADER_PATH.read_text() if HEADER_PATH.exists() else ""
        if current != rendered:
            print(
                "gen_mil_schema: MilSchema.h is out of date with the installed "
                "Core ML descriptors — run `python tools/gen_mil_schema.py`",
                file=sys.stderr,
            )
            return 1
        print("gen_mil_schema: MilSchema.h matches the descriptors")
        return 0

    HEADER_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEADER_PATH.write_text(rendered)
    n_fields = sum(len(v) for v in fields.values())
    print(
        f"[gen_mil_schema] {HEADER_PATH}  "
        f"({len(MESSAGES)} messages / {n_fields} fields / {len(enums)} enums)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
