#!/usr/bin/env python3
"""Phase 6.2 — Schema-driven Python type stub generator.

Reads lucid._C.engine at runtime (registry + introspection) and emits
``lucid/_C/engine.pyi`` for IDE type checking and autocomplete.

Usage:
    python tools/gen_pyi.py [--out PATH]

The file is re-generated on every run; commit the result alongside schema
changes.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path
from typing import Any

# Ensure the repo root is on sys.path.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from lucid._C import engine as E  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _dtype_str(t: Any) -> str:
    """Best-effort Python type annotation for a pybind11 attribute."""
    if t is None:
        return "None"
    name = getattr(t, "__name__", None) or str(t)
    return name


def _sig_or_fallback(fn: Any) -> str:
    """Return a best-effort signature string."""
    try:
        return str(inspect.signature(fn))
    except (ValueError, TypeError):
        return "(*args, **kwargs)"


def _collect_schemas() -> dict[str, Any]:
    return {s.name: s for s in E.op_registry_all()}


# ---------------------------------------------------------------------------
# Section writers
# ---------------------------------------------------------------------------

HEADER = '''\
# --------------------------------------------------------------------- #
# engine.pyi — auto-generated by tools/gen_pyi.py (Phase 6.2)          #
# DO NOT EDIT — regenerate with:  python tools/gen_pyi.py               #
# --------------------------------------------------------------------- #

from __future__ import annotations
from typing import List, Optional, Sequence, Tuple, Union

# ---- Enumerations -------------------------------------------------------

class Dtype:
    F16: Dtype
    F32: Dtype
    F64: Dtype
    I8: Dtype
    I16: Dtype
    I32: Dtype
    I64: Dtype
    Bool: Dtype

class Device:
    CPU: Device
    GPU: Device

class AmpPolicy:
    Promote: AmpPolicy
    KeepInput: AmpPolicy
    ForceFP32: AmpPolicy

# ---- Core types ---------------------------------------------------------

class TensorImpl:
    @property
    def shape(self) -> List[int]: ...
    @property
    def dtype(self) -> Dtype: ...
    @property
    def device(self) -> Device: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def numel(self) -> int: ...
    def data_as_python(self) -> List[float]: ...
    def grad_as_python(self) -> List[float]: ...
    def __init__(self, data: object, device: Device, requires_grad: bool) -> None: ...

class Generator:
    def __init__(self, seed: int) -> None: ...

class OpSchema:
    name: str
    version: int
    amp_policy: AmpPolicy
    deterministic: bool
    determinism_note: str
    input_arity: int
    output_arity: int
    stable_input_indices: List[int]

class AutocastGuard:
    def __init__(self, dtype: Dtype) -> None: ...

# ---- AMP API ------------------------------------------------------------

def amp_is_active() -> bool: ...
def amp_active_dtype() -> Optional[Dtype]: ...
def amp_policy_name(policy: AmpPolicy) -> str: ...

# ---- Determinism --------------------------------------------------------

def set_deterministic(value: bool) -> None: ...
def is_deterministic() -> bool: ...

# ---- Registry -----------------------------------------------------------

def op_registry_all() -> List[OpSchema]: ...
def op_registry_size() -> int: ...
def op_lookup(name: str) -> Optional[OpSchema]: ...
def schema_hash(schema: OpSchema) -> int: ...

# ---- Autograd -----------------------------------------------------------

def engine_backward(tensor: TensorImpl, retain_graph: bool = False) -> None: ...
def no_grad() -> object: ...
def is_grad_enabled() -> bool: ...

'''


def _write_op_stubs(schemas: dict[str, Any]) -> str:
    """Generate stubs for all registered ops, grouped by AmpPolicy."""
    lines: list[str] = ["# ---- Registered ops (from OpRegistry) --------------------------------\n"]

    # Collect all engine functions; pair with schema if available.
    seen: set[str] = set()
    for name in sorted(dir(E)):
        if name.startswith("_"):
            continue
        obj = getattr(E, name)
        if not callable(obj) or isinstance(obj, type):
            continue
        if name in seen:
            continue
        seen.add(name)

        schema = schemas.get(name)
        sig = _sig_or_fallback(obj)

        # Strip leading (self, ) if pybind11 injected it
        sig = sig.replace("(self, ", "(").replace("(self)", "()")

        policy_tag = ""
        if schema:
            policy_tag = f"  # {schema.amp_policy}, det={schema.deterministic}"

        lines.append(f"def {name}{sig} -> TensorImpl:{policy_tag}")
        lines.append("    ...")
        lines.append("")

    return "\n".join(lines)


def generate(out_path: Path) -> None:
    schemas = _collect_schemas()
    content = HEADER + _write_op_stubs(schemas)
    out_path.write_text(content, encoding="utf-8")
    print(f"[gen_pyi] wrote {out_path}  ({len(content.splitlines())} lines, "
          f"{len(schemas)} schemas)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=str(ROOT / "lucid" / "_C" / "engine.pyi"),
        help="Output path for the .pyi stub file.",
    )
    args = parser.parse_args()
    generate(Path(args.out))


if __name__ == "__main__":
    main()
