"""Write ``lucid/_annotation_names.py``: every name a module imports for type checkers.

Under PEP 649 a function's annotations are evaluated in its own module
globals when something asks for them — ``inspect.signature``, ``help()``,
an editor's tooltip, ``typing.get_type_hints``.  A name imported only inside
``if TYPE_CHECKING:`` is absent then, and the asking fails with
``NameError``.  :mod:`lucid._annotation_resolver` binds those names at run
time, once their sources exist; this tool records which they are, so that
nothing has to parse source at import time.

Usage::

    python -m tools.gen_annotation_names          # rewrite the table
    python -m tools.gen_annotation_names --check  # exit 1 if it is stale

``lucid/test/unit/test_public_signatures.py`` runs the check.
"""

import argparse
import ast
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "lucid"
OUT = PACKAGE / "_annotation_names.py"

Entry = tuple[str, str, str | None]


def _is_type_checking(test: ast.expr) -> bool:
    if isinstance(test, ast.Name):
        return test.id == "TYPE_CHECKING"
    return isinstance(test, ast.Attribute) and test.attr == "TYPE_CHECKING"


def _module_name(path: Path) -> str:
    parts = list(path.relative_to(ROOT).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _absolute(module: str, is_package: bool, level: int, target: str | None) -> str:
    if level == 0:
        return target or ""
    base = module.split(".") if is_package else module.split(".")[:-1]
    base = base[: len(base) - (level - 1)]
    return ".".join(base + ([target] if target else []))


def _entries(path: Path) -> list[Entry]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    module = _module_name(path)
    is_package = path.name == "__init__.py"
    found: list[Entry] = []
    for node in tree.body:
        if not (isinstance(node, ast.If) and _is_type_checking(node.test)):
            continue
        for stmt in node.body:
            if isinstance(stmt, ast.ImportFrom):
                source = _absolute(module, is_package, stmt.level, stmt.module)
                for alias in stmt.names:
                    if alias.name != "*":
                        found.append((alias.asname or alias.name, source, alias.name))
            elif isinstance(stmt, ast.Import):
                for alias in stmt.names:
                    if alias.asname:
                        found.append((alias.asname, alias.name, None))
                    else:
                        top = alias.name.split(".")[0]
                        found.append((top, top, None))
    return found


def collect() -> dict[str, tuple[Entry, ...]]:
    table: dict[str, tuple[Entry, ...]] = {}
    for path in sorted(PACKAGE.rglob("*.py")):
        if "test" in path.relative_to(PACKAGE).parts or path == OUT:
            continue
        entries = _entries(path)
        if entries:
            table[_module_name(path)] = tuple(sorted(set(entries)))
    return table


def render(table: dict[str, tuple[Entry, ...]]) -> str:
    lines = [
        '"""Generated by ``tools/gen_annotation_names.py`` — do not edit.',
        "",
        "Every name a module imports only under ``if TYPE_CHECKING:``, as",
        "``module -> ((bound name, source module, attribute or None), ...)``.",
        ":mod:`lucid._annotation_resolver` binds them once their sources exist.",
        '"""',
        "",
        "NAMES: dict[str, tuple[tuple[str, str, str | None], ...]] = {",
    ]

    def q(value: str | None) -> str:
        # Double-quoted, as black writes it, so formatting leaves the file alone.
        return "None" if value is None else json.dumps(value)

    for module, entries in table.items():
        rows = [f"({q(b)}, {q(s)}, {q(a)})" for b, s, a in entries]
        one_line = f"    {q(module)}: ({rows[0]},),"
        if len(rows) == 1 and len(one_line) <= 88:
            lines.append(one_line)  # black joins a lone entry that fits
            continue
        lines.append(f"    {q(module)}: (")
        for (b, s, a), row in zip(entries, rows):
            if len(f"        {row},") <= 88:
                lines.append(f"        {row},")
            else:  # as black splits an entry too long for the line
                lines.append("        (")
                lines.extend(f"            {q(v)}," for v in (b, s, a))
                lines.append("        ),")
        lines.append("    ),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if stale")
    args = parser.parse_args()
    text = render(collect())
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(
                f"{OUT.relative_to(ROOT)} is stale — run python -m tools.gen_annotation_names"
            )
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
