#!/usr/bin/env python3
"""
tools/gen_pyi.py — Regenerate the three public .pyi stub files.

Run as:  python tools/gen_pyi.py
Output:
  lucid/_C/engine.pyi        (introspected from the built C++ extension)
  lucid/_tensor/tensor.pyi   (Tensor class + registry methods)
  lucid/__init__.pyi         (top-level factories + registry free functions)
"""

import sys
import os
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


# ── Helpers ───────────────────────────────────────────────────────────────────


def _amp_policy_comment(name: str, policy_map: dict[str, str]) -> str:
    p = policy_map.get(name, "")
    if not p:
        return ""
    # normalise: "AmpPolicy.Promote" → "AmpPolicy.Promote"
    p = p.split(".")[-1]
    return f"  # AmpPolicy.{p}"


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# ── 1. engine.pyi ─────────────────────────────────────────────────────────────

_ENGINE_HEADER = """\
# --------------------------------------------------------------------- #
# engine.pyi — auto-generated by tools/gen_pyi.py
# DO NOT EDIT — regenerate with:  python tools/gen_pyi.py
# --------------------------------------------------------------------- #
# fmt: off

from typing import List, Optional, Sequence, SupportsFloat, SupportsInt

class Dtype:
    F16: Dtype
    F32: Dtype
    F64: Dtype
    BF16: Dtype
    I8: Dtype
    I16: Dtype
    I32: Dtype
    I64: Dtype
    Bool: Dtype
    C64: Dtype

class Device:
    CPU: Device
    GPU: Device

class AmpPolicy:
    Promote: AmpPolicy
    KeepInput: AmpPolicy
    ForceFP32: AmpPolicy

class TensorImpl:
    @property
    def shape(self) -> List[int]: ...
    @property
    def dtype(self) -> Dtype: ...
    @property
    def device(self) -> Device: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def is_metal_shared(self) -> bool: ...
    @property
    def grad_fn(self) -> Node | None: ...
    def numel(self) -> int: ...
    def data_as_python(self) -> object: ...
    def grad_as_python(self) -> object: ...
    def grad_as_impl(self) -> TensorImpl | None: ...
    def grad_to_tensor(self) -> TensorImpl | None: ...
    def set_grad(self, grad: TensorImpl) -> None: ...
    def zero_grad(self) -> None: ...
    def is_contiguous(self) -> bool: ...
    def bump_version(self) -> None: ...
    def clone_with_grad(self, requires_grad: bool = ...) -> TensorImpl: ...
    def copy_from(self, other: TensorImpl) -> None: ...
    def to_string(self, precision: int, threshold: int, edgeitems: int) -> str: ...
    def eval(self) -> None: ...
    def item(self) -> float | int | bool: ...
    def retain_grad_(self) -> None: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: bytes, shape: List[int], dtype: Dtype, device: Device, requires_grad: bool) -> TensorImpl: ...
    def transfer_to_device(self, target: Device, requires_grad: bool) -> TensorImpl: ...
    def tolist(self) -> object: ...
    def __init__(self, data: object, device: Device, requires_grad: bool) -> None: ...

class Node: ...

class Generator:
    def __init__(self, seed: int) -> None: ...
    def set_seed(self, seed: int) -> None: ...
    @property
    def seed(self) -> int: ...
    @property
    def counter(self) -> int: ...
    def next_uniform_float(self) -> float: ...

class OpSchema:
    name: str
    version: int
    amp_policy: AmpPolicy
    deterministic: bool
    input_arity: int
    output_arity: int

class OpEvent:
    name: str
    time_ns: int
    shape: List[int]
    flops: int
    memory_delta_bytes: int

class MemoryStats:
    current_bytes: int
    peak_bytes: int
    alloc_count: int
    free_count: int

class Profiler:
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def events(self) -> List[OpEvent]: ...
    def reset(self) -> None: ...
    def clear(self) -> None: ...

class _nn_namespace:
    # Stub for the ``_C_engine.nn`` sub-namespace (C++ nn ops).
    @staticmethod
    def linear(x: TensorImpl, w: TensorImpl, b: TensorImpl | None) -> TensorImpl: ...
    @staticmethod
    def bilinear_layer(x1: TensorImpl, x2: TensorImpl, w: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def conv1d(x: TensorImpl, w: TensorImpl, b: TensorImpl | None, stride: int, padding: int, dilation: int, groups: int) -> TensorImpl: ...
    @staticmethod
    def conv2d(x: TensorImpl, w: TensorImpl, b: TensorImpl | None, stride_h: int, stride_w: int, pad_h: int, pad_w: int, dil_h: int, dil_w: int, groups: int) -> TensorImpl: ...
    @staticmethod
    def conv3d(x: TensorImpl, w: TensorImpl, b: TensorImpl | None, stride_d: int, stride_h: int, stride_w: int, pad_d: int, pad_h: int, pad_w: int, dil_d: int, dil_h: int, dil_w: int, groups: int) -> TensorImpl: ...
    @staticmethod
    def conv_transpose1d(x: TensorImpl, w: TensorImpl, b: TensorImpl | None, stride: int, pad: int, opad: int) -> TensorImpl: ...
    @staticmethod
    def conv_transpose2d(x: TensorImpl, w: TensorImpl, b: TensorImpl | None, stride_h: int, stride_w: int, pad_h: int, pad_w: int, opad_h: int, opad_w: int) -> TensorImpl: ...
    @staticmethod
    def conv_transpose3d(x: TensorImpl, w: TensorImpl, b: TensorImpl | None, stride_d: int, stride_h: int, stride_w: int, pad_d: int, pad_h: int, pad_w: int, opad_d: int, opad_h: int, opad_w: int) -> TensorImpl: ...
    @staticmethod
    def max_pool1d(x: TensorImpl, k: int, s: int, p: int) -> TensorImpl: ...
    @staticmethod
    def max_pool2d(x: TensorImpl, kh: int, kw: int, sh: int, sw: int, ph: int, pw: int) -> TensorImpl: ...
    @staticmethod
    def max_pool3d(x: TensorImpl, kd: int, kh: int, kw: int, sd: int, sh: int, sw: int, pd: int, ph: int, pw: int) -> TensorImpl: ...
    @staticmethod
    def avg_pool1d(x: TensorImpl, k: int, s: int, p: int) -> TensorImpl: ...
    @staticmethod
    def avg_pool2d(x: TensorImpl, kh: int, kw: int, sh: int, sw: int, ph: int, pw: int) -> TensorImpl: ...
    @staticmethod
    def avg_pool3d(x: TensorImpl, kd: int, kh: int, kw: int, sd: int, sh: int, sw: int, pd: int, ph: int, pw: int) -> TensorImpl: ...
    @staticmethod
    def adaptive_avg_pool1d(x: TensorImpl, sz: int) -> TensorImpl: ...
    @staticmethod
    def adaptive_avg_pool2d(x: TensorImpl, oh: int, ow: int) -> TensorImpl: ...
    @staticmethod
    def adaptive_avg_pool3d(x: TensorImpl, od: int, oh: int, ow: int) -> TensorImpl: ...
    @staticmethod
    def adaptive_max_pool1d(x: TensorImpl, sz: int) -> TensorImpl: ...
    @staticmethod
    def adaptive_max_pool2d(x: TensorImpl, oh: int, ow: int) -> TensorImpl: ...
    @staticmethod
    def adaptive_max_pool3d(x: TensorImpl, od: int, oh: int, ow: int) -> TensorImpl: ...
    @staticmethod
    def batch_norm(x: TensorImpl, w: TensorImpl, b: TensorImpl, rm: TensorImpl, rv: TensorImpl, training: bool, momentum: float, eps: float) -> TensorImpl: ...
    @staticmethod
    def batch_norm1d(x: TensorImpl, w: TensorImpl, b: TensorImpl, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def batch_norm3d(x: TensorImpl, w: TensorImpl, b: TensorImpl, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def batch_norm_eval(x: TensorImpl, rm: TensorImpl, rv: TensorImpl, w: TensorImpl, b: TensorImpl, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def layer_norm(x: TensorImpl, w: TensorImpl, b: TensorImpl, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def group_norm(x: TensorImpl, w: TensorImpl, b: TensorImpl, num_groups: int, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def rms_norm(x: TensorImpl, w: TensorImpl, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def lp_normalize(x: TensorImpl, ord: float, dim: int, eps: float = ...) -> TensorImpl: ...
    @staticmethod
    def embedding(w: TensorImpl, x: TensorImpl, pad: int) -> TensorImpl: ...
    @staticmethod
    def embedding_bag(w: TensorImpl, x: TensorImpl, offsets: TensorImpl, mode: int, padding_idx: int, include_last_offset: bool) -> TensorImpl: ...
    @staticmethod
    def one_hot(x: TensorImpl, num_classes: int) -> TensorImpl: ...
    @staticmethod
    def dropout(x: TensorImpl, p: float, training: bool) -> TensorImpl: ...
    @staticmethod
    def dropoutnd(x: TensorImpl, p: float, training: bool) -> TensorImpl: ...
    @staticmethod
    def alpha_dropout(x: TensorImpl, p: float, training: bool) -> TensorImpl: ...
    @staticmethod
    def scaled_dot_product_attention(q: TensorImpl, k: TensorImpl, v: TensorImpl, mask: TensorImpl | None, scale: float, is_causal: bool) -> TensorImpl: ...
    @staticmethod
    def lstm_forward(x: TensorImpl, h0: TensorImpl, c0: TensorImpl, weights: list[TensorImpl], hidden_size: int, num_layers: int, batch_first: bool, bidirectional: bool, training: bool, proj_size: int) -> tuple[TensorImpl, TensorImpl, TensorImpl]: ...
    @staticmethod
    def mse_loss(input: TensorImpl, target: TensorImpl, reduction: int) -> TensorImpl: ...
    @staticmethod
    def huber_loss(input: TensorImpl, target: TensorImpl, delta: float, reduction: int) -> TensorImpl: ...
    @staticmethod
    def ctc_loss(input: TensorImpl, targets: TensorImpl, input_lengths: TensorImpl, target_lengths: TensorImpl, blank: int, zero_infinity: bool) -> TensorImpl: ...
    @staticmethod
    def fold(x: TensorImpl, output_size: list[int], kernel_size: list[int], stride: list[int], padding: list[int], dilation: list[int]) -> TensorImpl: ...
    @staticmethod
    def unfold(x: TensorImpl, kernel: list[int], stride: list[int], pad: list[int], dilation: list[int]) -> TensorImpl: ...
    @staticmethod
    def grid_sample(x: TensorImpl, grid: TensorImpl, align_corners: bool) -> TensorImpl: ...
    @staticmethod
    def affine_grid(theta: TensorImpl, N: int, H: int, W: int, align_corners: bool) -> TensorImpl: ...
    @staticmethod
    def interpolate_nearest_2d(x: TensorImpl, oh: int, ow: int) -> TensorImpl: ...
    @staticmethod
    def interpolate_nearest_3d(x: TensorImpl, od: int, oh: int, ow: int) -> TensorImpl: ...
    @staticmethod
    def interpolate_bilinear(x: TensorImpl, oh: int, ow: int, align_corners: bool) -> TensorImpl: ...
    @staticmethod
    def interpolate_trilinear(x: TensorImpl, od: int, oh: int, ow: int, align_corners: bool) -> TensorImpl: ...

nn: _nn_namespace

class AutocastGuard:
    def __init__(self, dtype: Dtype) -> None: ...
    def __enter__(self) -> AutocastGuard: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: object) -> None: ...

# Module-level Dtype aliases (same objects as Dtype.F32 etc.)
F16: Dtype
F32: Dtype
F64: Dtype
BF16: Dtype
I8: Dtype
I16: Dtype
I32: Dtype
I64: Dtype
Bool: Dtype
C64: Dtype

# Module-level Device aliases
CPU: Device
GPU: Device

ABI_VERSION: int

def amp_is_active() -> bool: ...
def amp_active_dtype() -> Optional[Dtype]: ...
def set_deterministic(value: bool) -> None: ...
def is_deterministic() -> bool: ...
def op_registry_all() -> List[OpSchema]: ...
def op_registry_size() -> int: ...
def op_lookup(name: str) -> Optional[OpSchema]: ...
def engine_backward(tensor: TensorImpl, retain_graph: bool = False) -> None: ...
def no_grad() -> object: ...
def is_grad_enabled() -> bool: ...

# ---- Ops (introspected from built engine) -----------------------------------

"""


_ENGINE_FOOTER = """
# ── C++ optimizer classes ──────────────────────────────────────────────────
class _EngineOptimizer:
    \"\"\"Base for all C++ engine optimizer classes.\"\"\"
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Adam(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., beta1: float = ..., beta2: float = ..., eps: float = ..., weight_decay: float = ...) -> None: ...

class AdamW(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., beta1: float = ..., beta2: float = ..., eps: float = ..., weight_decay: float = ...) -> None: ...

class SGD(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., momentum: float = ..., dampening: float = ..., weight_decay: float = ...) -> None: ...

class RMSprop(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., alpha: float = ..., eps: float = ..., weight_decay: float = ..., momentum: float = ..., centered: bool = ...) -> None: ...

class Adagrad(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., eps: float = ..., weight_decay: float = ..., initial_accumulator_value: float = ...) -> None: ...

class Adadelta(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., rho: float = ..., eps: float = ..., weight_decay: float = ...) -> None: ...

class Adamax(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., beta1: float = ..., beta2: float = ..., eps: float = ..., weight_decay: float = ...) -> None: ...

class RAdam(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., beta1: float = ..., beta2: float = ..., eps: float = ..., weight_decay: float = ...) -> None: ...

class NAdam(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., beta1: float = ..., beta2: float = ..., eps: float = ..., weight_decay: float = ..., momentum_decay: float = ...) -> None: ...

class ASGD(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., lambd: float = ..., alpha: float = ..., t0: float = ..., weight_decay: float = ...) -> None: ...

class Rprop(_EngineOptimizer):
    def __init__(self, params: list[TensorImpl], lr: float = ..., eta_minus: float = ..., eta_plus: float = ..., step_min: float = ..., step_max: float = ...) -> None: ...

# ── _C_engine.linalg sub-namespace ────────────────────────────────────────
class _linalg_namespace:
    \"\"\"Stub for the ``_C_engine.linalg`` sub-namespace (C++ linalg ops).\"\"\"
    @staticmethod
    def norm(a: TensorImpl, ord: float = ..., dim: list[int] = ..., keepdims: bool = ...) -> TensorImpl: ...
    @staticmethod
    def det(a: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def inv(a: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def pinv(a: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def solve(a: TensorImpl, b: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def qr(a: TensorImpl) -> tuple[TensorImpl, TensorImpl]: ...
    @staticmethod
    def svd(a: TensorImpl, compute_uv: bool = ...) -> tuple[TensorImpl, TensorImpl, TensorImpl]: ...
    @staticmethod
    def eig(a: TensorImpl) -> tuple[TensorImpl, TensorImpl]: ...
    @staticmethod
    def eigh(a: TensorImpl) -> tuple[TensorImpl, TensorImpl]: ...
    @staticmethod
    def cholesky(a: TensorImpl, upper: bool = ...) -> TensorImpl: ...
    @staticmethod
    def lu_factor(a: TensorImpl) -> tuple[TensorImpl, TensorImpl]: ...
    @staticmethod
    def lu_solve(b: TensorImpl, lu: TensorImpl, piv: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def lstsq(a: TensorImpl, b: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def solve_triangular(a: TensorImpl, b: TensorImpl, upper: bool, unitriangular: bool = ...) -> TensorImpl: ...
    @staticmethod
    def householder_product(a: TensorImpl, tau: TensorImpl) -> TensorImpl: ...
    @staticmethod
    def ldl_factor(a: TensorImpl) -> tuple[TensorImpl, TensorImpl]: ...
    @staticmethod
    def foo(a: TensorImpl) -> TensorImpl: ...

linalg: _linalg_namespace

# ── einops sub-namespace ──────────────────────────────────────────────────────

class _einops_namespace:
    @staticmethod
    def rearrange(a: TensorImpl, pattern: str, axes_lengths: dict[str, int]) -> TensorImpl: ...
    @staticmethod
    def reduce(a: TensorImpl, pattern: str, reduction: str, axes_lengths: dict[str, int]) -> TensorImpl: ...
    @staticmethod
    def repeat(a: TensorImpl, pattern: str, axes_lengths: dict[str, int]) -> TensorImpl: ...
    @staticmethod
    def einsum(pattern: str, *tensors: TensorImpl) -> TensorImpl: ...

einops: _einops_namespace

# ── Fused kernels & Metal runner ─────────────────────────────────────────────

def _fused_linear_relu(x: TensorImpl, weight: TensorImpl, bias: TensorImpl | None) -> TensorImpl: ...
def _fused_linear_gelu(x: TensorImpl, weight: TensorImpl, bias: TensorImpl | None) -> TensorImpl: ...
def _run_metal_kernel(source: str, kernel_name: str, inputs: list[TensorImpl], output_shape: list[int], output_dtype: Dtype, threads_per_grid: list[int], threads_per_group: list[int]) -> TensorImpl: ...

# ── Custom autograd (Python-defined Function) ─────────────────────────────────

class FunctionCtx:
    def save_for_backward(self, *tensors: TensorImpl) -> None: ...
    def saved_tensors(self) -> tuple[TensorImpl, ...]: ...
    def __setattr__(self, key: str, value: object) -> None: ...
    def __getattr__(self, key: str) -> object: ...

class _PythonBackwardNode:
    ctx: FunctionCtx
    backward_fn: object

def _register_python_backward_node(
    output: TensorImpl,
    node: _PythonBackwardNode,
    inputs: list[TensorImpl],
) -> None: ...
"""


def gen_engine_pyi() -> str:
    from lucid._C import engine as e

    # Build amp policy map from the op registry
    policy_map: dict[str, str] = {}
    try:
        for schema in e.op_registry_all():
            policy_map[schema.name] = str(schema.amp_policy)
    except Exception:
        pass

    # All callable non-class members (excludes classes like Dtype, TensorImpl, etc.)
    skip_classes = {x for x in dir(e) if isinstance(getattr(e, x, None), type)}
    skip_fixed = {
        "amp_is_active",
        "amp_active_dtype",
        "set_deterministic",
        "is_deterministic",
        "op_registry_all",
        "op_registry_size",
        "op_lookup",
        "engine_backward",
        "no_grad",
        "is_grad_enabled",
        "ABI_VERSION",
    }
    names = sorted(
        x
        for x in dir(e)
        if not x.startswith("_")
        and x not in skip_classes
        and x not in skip_fixed
        and callable(getattr(e, x, None))
    )

    lines = []
    for name in names:
        comment = _amp_policy_comment(name, policy_map)
        sig_str = _engine_fn_sig(name, getattr(e, name))
        if comment:
            lines.append(f"def {name}{sig_str}:{comment}")
            lines.append("    ...")
            lines.append("")
        else:
            lines.append(f"def {name}{sig_str}: ...")

    # Apply per-function overrides for signatures that the C++ docstring
    # doesn't capture correctly (e.g. Optional arguments not reflected).
    _SIG_OVERRIDES: dict[str, str] = {
        "set_current_profiler": "(profiler: Profiler | None) -> None",
    }
    for i, line in enumerate(lines):
        for fn_name, override_sig in _SIG_OVERRIDES.items():
            if line.startswith(f"def {fn_name}"):
                lines[i] = f"def {fn_name}{override_sig}: ..."
                break

    # Count for summary
    count = len(names)
    return _ENGINE_HEADER + "\n".join(lines) + _ENGINE_FOOTER, count


def _engine_fn_sig(name: str, fn: object) -> str:
    """Parse a pybind11 builtin's first-line docstring into ``(...) -> R``.

    pybind11 emits a self-describing signature on line 1 of every function's
    ``__doc__`` — we lift that directly so engine.pyi mirrors the real C++
    surface (with concrete dtypes, defaults, and return type) instead of
    a uselessly generic ``*args, **kwargs``.

    Falls back to a tensor-pass-through signature when parsing fails — the
    project policy forbids ``Any`` in stubs.
    """
    import re

    doc = getattr(fn, "__doc__", "") or ""
    first = doc.splitlines()[0] if doc else ""
    # pybind11 lines look like:  name(arg: Type [= dflt], ...) -> RetType
    m = re.match(
        rf"^{re.escape(name)}\((?P<params>.*)\)\s*->\s*(?P<ret>.+?)\s*$", first
    )
    if not m:
        return "(input: TensorImpl, /, *args: object, **kwargs: object) -> TensorImpl"
    params_raw = m.group("params").strip()
    ret_raw = _engine_strip(m.group("ret").strip())

    # Top-level comma-split that respects nested brackets.
    params: list[str] = []
    depth = 0
    cur = ""
    for ch in params_raw + ",":
        if ch == "," and depth == 0:
            piece = cur.strip()
            cur = ""
            if not piece:
                continue
            params.append(_engine_param(piece))
        else:
            if ch in "[(":
                depth += 1
            elif ch in "])":
                depth -= 1
            cur += ch
    # Python forbids a positional-with-default followed by a positional
    # without one — pybind11 doesn't enforce that, so strip leftover defaults
    # from any param that appears before a non-defaulted positional.
    last_no_default = -1
    for i, p in enumerate(params):
        if "= ..." not in p and not p.startswith("*"):
            last_no_default = i
    for i in range(last_no_default):
        if params[i].endswith(" = ...") and not params[i].startswith("*"):
            params[i] = params[i][: -len(" = ...")]
    return f"({', '.join(params)}) -> {ret_raw}"


def _engine_param(piece: str) -> str:
    """Render one parsed engine parameter — ``name: type [= ...]``."""
    if "=" in piece:
        head, _ = piece.split("=", 1)
        head = head.strip()
        return f"{_engine_strip_param(head)} = ..."
    return _engine_strip_param(piece)


def _engine_strip_param(piece: str) -> str:
    if ":" in piece:
        pname, ann = piece.split(":", 1)
        return f"{pname.strip()}: {_engine_strip(ann.strip())}"
    return piece


def _engine_strip(t: str) -> str:
    """Normalise a pybind11 type string for use inside a stub."""
    t = t.replace("lucid._C.engine.", "")
    t = t.replace("collections.abc.", "")
    t = t.replace("typing.", "")
    t = t.replace("NoneType", "None")
    return t


# ── 2. tensor.pyi ─────────────────────────────────────────────────────────────

_TENSOR_HEADER = """\
# --------------------------------------------------------------------- #
# tensor.pyi — auto-generated by tools/gen_pyi.py
# DO NOT EDIT — regenerate with:  python tools/gen_pyi.py
# --------------------------------------------------------------------- #
# fmt: off

from typing import Iterator, Self, Sequence, overload
import builtins

import numpy as np

from lucid._C import engine as _C_engine
from lucid._dtype import dtype as _dtype_cls
from lucid._device import device as _device_cls
from lucid._types import DeviceLike, DTypeLike, DimLike, ShapeLike, Scalar, TensorOrScalar, _IndexType  # noqa: F401

# Aliases for builtins that get shadowed by same-named Tensor methods below.
_float = builtins.float
_int = builtins.int
_bool = builtins.bool

class Tensor:

    # ── directly defined ────────────────────────────────────────────────
    _impl: _C_engine.TensorImpl  # raw impl — mutable by _apply() in nn.Module

    @classmethod
    def __new_from_impl__(cls, impl: _C_engine.TensorImpl) -> Self: ...

    def __init__(
        self,
        data: np.ndarray | list[object] | int | float | bool | Tensor,
        *,
        dtype: _dtype_cls | _C_engine.Dtype | str | None = None,
        device: _device_cls | str | None = None,
        requires_grad: bool = False,
    ) -> None: ...
    @property
    def impl(self) -> _C_engine.TensorImpl: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> _dtype_cls: ...
    @property
    def device(self) -> _device_cls: ...
    @property
    def ndim(self) -> int: ...
    @property
    def T(self) -> Self: ...
    @property
    def mT(self) -> Self: ...
    @property
    def is_metal(self) -> bool: ...
    @property
    def is_shared(self) -> bool: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def requires_grad(self) -> bool: ...
    @requires_grad.setter
    def requires_grad(self, v: bool) -> None: ...
    def numel(self) -> int: ...
    def dim(self) -> int: ...
    @overload
    def size(self, dim: int) -> int: ...
    @overload
    def size(self, dim: None = ...) -> tuple[int, ...]: ...
    def is_contiguous(self) -> bool: ...
    @property
    def grad(self) -> Self | None: ...
    @grad.setter
    def grad(self, v: Tensor | None) -> None: ...
    @property
    def grad_fn(self) -> _C_engine.Node | None: ...
    def requires_grad_(self, requires_grad: bool = True) -> Self: ...
    def retain_grad(self) -> None: ...
    def backward(
        self,
        gradient: Tensor | None = None,
        retain_graph: bool = False,
        create_graph: bool = False,
    ) -> None: ...
    def detach(self) -> Self: ...
    def detach_(self) -> Self: ...
    def clamp_(self, min: float | None = None, max: float | None = None) -> Self: ...
    def clamp_min_(self, min: float) -> Self: ...
    def clamp_max_(self, max: float) -> Self: ...
    def clone(self) -> Self: ...
    def item(self) -> float | int | bool: ...
    def numpy(self) -> np.ndarray: ...
    def tolist(self) -> list[object] | int | float | bool: ...
    def contiguous(self) -> Self: ...
    def unfold(self, dimension: int, size: int, step: int) -> Tensor: ...
    @property
    def data(self) -> Self: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[Self]: ...
    def __format__(self, format_spec: str) -> str: ...
    def new_empty(
        self,
        *size: int,
        dtype: _dtype_cls | None = None,
        device: _device_cls | str | None = None,
        requires_grad: bool = False,
    ) -> Self: ...
    def new_zeros(
        self,
        *size: int,
        dtype: _dtype_cls | None = None,
        device: _device_cls | str | None = None,
        requires_grad: bool = False,
    ) -> Self: ...
    def new_ones(
        self,
        *size: int,
        dtype: _dtype_cls | None = None,
        device: _device_cls | str | None = None,
        requires_grad: bool = False,
    ) -> Self: ...
    def new_full(
        self,
        size: tuple[int, ...],
        fill_value: float,
        dtype: _dtype_cls | None = None,
        device: _device_cls | str | None = None,
        requires_grad: bool = False,
    ) -> Self: ...
    def new_tensor(
        self,
        data: np.ndarray | list[object] | int | float | bool | Tensor,
        dtype: _dtype_cls | None = None,
        device: _device_cls | str | None = None,
        requires_grad: bool = False,
    ) -> Self: ...
    def element_size(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def is_floating_point(self) -> bool: ...
    def is_complex(self) -> bool: ...
    def share_memory_(self) -> Self: ...
    def fill_(self, value: float) -> Self: ...
    def copy_(self, other: Self) -> Self: ...
    def flip(self, dims: int | list[int] | Sequence[int]) -> Self: ...
    def fliplr(self) -> Self: ...
    def flipud(self) -> Self: ...
    def index_select(self, dim: int, index: Self) -> Self: ...
    def masked_select(self, mask: Self) -> Self: ...
    def expand_as(self, other: Self) -> Self: ...
    def view_as(self, other: Self) -> Self: ...
    def type_as(self, other: Self) -> Self: ...
    def lerp(self, end: Self, weight: float | Self) -> Self: ...
    def where(self, condition: Self, other: Self | float) -> Self: ...
    def diff(self, n: int = 1, dim: int = -1) -> Self: ...
    def addmm(
        self, mat1: Self, mat2: Self, beta: float = 1.0, alpha: float = 1.0
    ) -> Self: ...
    def bmm(self, mat2: Self) -> Tensor: ...
    def zero_(self) -> Self: ...

    # ── injected dunders (_dunders.py) ──────────────────────────────────
    def __add__(self, other: TensorOrScalar) -> Tensor: ...
    def __radd__(self, other: TensorOrScalar) -> Tensor: ...
    def __iadd__(self, other: TensorOrScalar) -> Tensor: ...
    def __sub__(self, other: TensorOrScalar) -> Tensor: ...
    def __rsub__(self, other: TensorOrScalar) -> Tensor: ...
    def __isub__(self, other: TensorOrScalar) -> Tensor: ...
    def __mul__(self, other: TensorOrScalar) -> Tensor: ...
    def __rmul__(self, other: TensorOrScalar) -> Tensor: ...
    def __imul__(self, other: TensorOrScalar) -> Tensor: ...
    def __truediv__(self, other: TensorOrScalar) -> Tensor: ...
    def __rtruediv__(self, other: TensorOrScalar) -> Tensor: ...
    def __itruediv__(self, other: TensorOrScalar) -> Tensor: ...
    def __floordiv__(self, other: TensorOrScalar) -> Tensor: ...
    def __rfloordiv__(self, other: TensorOrScalar) -> Tensor: ...
    def __pow__(self, other: TensorOrScalar) -> Tensor: ...
    def __rpow__(self, other: TensorOrScalar) -> Tensor: ...
    def __ipow__(self, other: TensorOrScalar) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __rmatmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __abs__(self) -> Tensor: ...
    def __invert__(self) -> Tensor: ...
    def __and__(self, other: TensorOrScalar) -> Tensor: ...
    def __or__(self, other: TensorOrScalar) -> Tensor: ...
    def __xor__(self, other: TensorOrScalar) -> Tensor: ...
    def __eq__(self, other: object) -> Tensor: ...  # type: ignore[override]  # Tensor equality returns Tensor not bool
    def __ne__(self, other: object) -> Tensor: ...  # type: ignore[override]  # Tensor inequality returns Tensor not bool
    def __lt__(self, other: TensorOrScalar) -> Tensor: ...
    def __le__(self, other: TensorOrScalar) -> Tensor: ...
    def __gt__(self, other: TensorOrScalar) -> Tensor: ...
    def __ge__(self, other: TensorOrScalar) -> Tensor: ...
    def __getitem__(self, idx: _IndexType) -> Tensor: ...
    def __setitem__(self, idx: _IndexType, value: TensorOrScalar) -> None: ...

    # ── injected .to() and device/dtype casts (_to.py) ─────────────────
    def to(self, device: DeviceLike | DTypeLike | Tensor | None = None, dtype: DTypeLike | None = None, *, copy: _bool = False) -> Tensor: ...
    def metal(self) -> Tensor: ...
    def cpu(self) -> Tensor: ...
    def float(self) -> Tensor: ...
    def double(self) -> Tensor: ...
    def half(self) -> Tensor: ...
    def int(self) -> Tensor: ...
    def long(self) -> Tensor: ...
    def bool(self) -> Tensor: ...

    # ── registry-injected ops (_registry.py) ────────────────────────────
"""


def _tensor_method_sig(entry) -> str:
    """Generate a method signature line for a registry entry."""
    name = entry.method_name
    n = entry.n_tensor_args

    if n == -1:
        return f"    def {name}(self, tensors: list[Tensor]) -> Tensor: ..."

    extra = entry.extra_kwargs

    if n == 1 and not extra:
        return f"    def {name}(self) -> Tensor: ..."

    if n == 2 and not extra:
        return f"    def {name}(self, other: Tensor | _float) -> Tensor: ..."

    # Has extra kwargs — emit explicit signature via _PARAM_TYPE_MAP lookup
    # rather than *args/**kwargs (H9: banned in stubs).
    parts = []
    if n == 2:
        parts.append("other: Tensor | _float")
    if extra:
        for kw in (extra if isinstance(extra, (list, tuple)) else []):
            ptype = _PARAM_TYPE_MAP.get(kw, "object")
            parts.append(f"{kw}: {ptype} = ...")
    args_str = (", " + ", ".join(parts)) if parts else ""
    return f"    def {name}(self{args_str}) -> Tensor: ..."


def gen_tensor_pyi() -> tuple[str, int]:
    from lucid._ops._registry import _REGISTRY

    # Methods that have explicit, hand-crafted signatures in ``python_only``
    # below — skip the simplified registry stubs to avoid duplicate definitions.
    _PYTHON_ONLY_METHODS: frozenset[str] = frozenset(
        {
            # Reduction / statistical ops (hand-crafted with DimLike)
            "sum",
            "mean",
            "prod",
            "max",
            "min",
            "var",
            "std",
            "argmax",
            "argmin",
            "cumsum",
            "cumprod",
            "cummax",
            "cummin",
            # Shape / layout ops
            "squeeze",
            "unsqueeze",
            "gather",
            "sort",
            "argsort",
            "topk",
            "softmax",
            "log_softmax",
            "clip",
            "clamp",
            "repeat",
            "repeat_interleave",
            "split",
            "any",
            "all",
            "t",
            "view",
            "narrow",
            "scatter",
            "kthvalue",
            "movedim",
            "unflatten",
            "histc",
            # Comparison / bitwise (hand-crafted to use _float)
            "eq",
            "ne",
            "lt",
            "le",
            "gt",
            "ge",
            "bitwise_and",
            "bitwise_or",
            "bitwise_xor",
            "bitwise_left_shift",
            "bitwise_right_shift",
            "isclose",
            "scatter_add",
            # Methods already in _TENSOR_HEADER — must not be re-emitted by
            # the registry loop or they would produce [no-redef] duplicates.
            "bmm",
            "broadcast_to",
            "chunk",
            "contiguous",
            "detach",
            "diagonal",
            "erf",
            "erfinv",
            "expand",
            "expand_dims",
            "flatten",
            "flip",
            "fliplr",
            "flipud",
            "index_select",
            "isfinite",
            "isinf",
            "isnan",
            "masked_fill",
            "masked_select",
            "nan_to_num",
            "nonzero",
            "pad",
            "permute",
            "ravel",
            "reshape",
            "roll",
            "rsqrt",
            "squeeze_all",
            "swapaxes",
            "tile",
            "trace",
            "transpose",
            "tril",
            "triu",
            "unbind",
            # Additional TENSOR_HEADER methods that registry also has
            "clone",
            "detach",
            "lerp",
            "where",
            "diff",
            "bmm",
            "zero_",
            "fill_",
            "copy_",
        }
    )

    lines = []
    count = 0
    for entry in _REGISTRY:
        mn = entry.method_name
        if mn is None or mn.startswith("__"):
            continue
        if mn in _PYTHON_ONLY_METHODS:
            continue
        lines.append(_tensor_method_sig(entry))
        count += 1

    # Also add the Python-only methods that override registry (from _methods.py).
    # Uses _int / _bool / DimLike aliases — defined in the stub header above.
    python_only = [
        "    def sum(self, dim: DimLike = None, keepdim: _bool = False, *, correction: _int = 1) -> Tensor: ...",
        "    def mean(self, dim: DimLike = None, keepdim: _bool = False) -> Tensor: ...",
        "    def prod(self, dim: DimLike = None, keepdim: _bool = False) -> Tensor: ...",
        "    def max(self, dim: DimLike = None, keepdim: _bool = False) -> Tensor: ...",
        "    def min(self, dim: DimLike = None, keepdim: _bool = False) -> Tensor: ...",
        "    def var(self, dim: DimLike = None, keepdim: _bool = False, *, correction: _int = 1) -> Tensor: ...",
        "    def std(self, dim: DimLike = None, keepdim: _bool = False, *, correction: _int = 1) -> Tensor: ...",
        "    def argmax(self, dim: _int | None = None, keepdim: _bool = False) -> Tensor: ...",
        "    def argmin(self, dim: _int | None = None, keepdim: _bool = False) -> Tensor: ...",
        "    def cumsum(self, dim: _int | None = None) -> Tensor: ...",
        "    def cumprod(self, dim: _int | None = None) -> Tensor: ...",
        "    def cummax(self, dim: _int | None = None) -> Tensor: ...",
        "    def cummin(self, dim: _int | None = None) -> Tensor: ...",
        "    def squeeze(self, dim: _int | list[_int] | None = None) -> Tensor: ...",
        "    def unsqueeze(self, dim: DimLike = None) -> Tensor: ...",
        "    def gather(self, other: Tensor | _float, dim: DimLike = None) -> Tensor: ...",
        "    def sort(self, dim: DimLike = None, descending: _bool = False) -> Tensor: ...",
        "    def argsort(self, dim: DimLike = None, descending: _bool = False) -> Tensor: ...",
        "    def topk(self, k: _int, dim: DimLike = None, largest: _bool = True) -> Tensor: ...",
        "    def softmax(self, axis: _int = -1) -> Tensor: ...",
        "    def log_softmax(self, axis: _int = -1) -> Tensor: ...",
        "    def clip(self, min: Scalar | None = None, max: Scalar | None = None) -> Tensor: ...",
        "    def clamp(self, min: Scalar | None = None, max: Scalar | None = None) -> Tensor: ...",
        "    def repeat(self, *sizes: _int) -> Tensor: ...",
        "    def repeat_interleave(self, repeats: _int, dim: _int | None = None) -> Tensor: ...",
        "    def split(self, split_size_or_sections: _int | list[_int], dim: _int = 0) -> list[Tensor]: ...",
        "    def any(self) -> Tensor: ...",
        "    def all(self) -> Tensor: ...",
        "    def t(self) -> Tensor: ...",
        "    def view(self, *shape: _int | tuple[_int, ...]) -> Tensor: ...",
        "    def narrow(self, dim: _int, start: _int, length: _int) -> Tensor: ...",
        "    def scatter(self, dim: _int, index: Tensor, src: Tensor | _float, reduce: str | None = None) -> Tensor: ...",
        "    def kthvalue(self, k: _int, dim: _int = -1, keepdim: _bool = False) -> Tensor: ...",
        "    def movedim(self, source: _int | Sequence[_int], destination: _int | Sequence[_int]) -> Tensor: ...",
        "    def flatten(self, start: _int = 0, end: _int = -1) -> Tensor: ...",
        "    def unflatten(self, dim: _int, sizes: Sequence[_int]) -> Tensor: ...",
        "    def histc(self, bins: _int = 100, min: _float = 0.0, max: _float = 0.0) -> Tensor: ...",
        "    def eq(self, other: Tensor | _float) -> Tensor: ...",
        "    def ne(self, other: Tensor | _float) -> Tensor: ...",
        "    def lt(self, other: Tensor | _float) -> Tensor: ...",
        "    def le(self, other: Tensor | _float) -> Tensor: ...",
        "    def gt(self, other: Tensor | _float) -> Tensor: ...",
        "    def ge(self, other: Tensor | _float) -> Tensor: ...",
        "    def bitwise_and(self, other: Tensor | _float) -> Tensor: ...",
        "    def bitwise_or(self, other: Tensor | _float) -> Tensor: ...",
        "    def bitwise_xor(self, other: Tensor | _float) -> Tensor: ...",
        "    def bitwise_left_shift(self, other: Tensor | _float) -> Tensor: ...",
        "    def bitwise_right_shift(self, other: Tensor | _float) -> Tensor: ...",
        "    def isclose(self, other: Tensor | _float, rtol: _float = 1e-5, atol: _float = 1e-8, equal_nan: _bool = False) -> Tensor: ...",
        "    def scatter_add(self, dim: _int, index: Tensor, src: Tensor) -> Tensor: ...",
        # Methods in _TENSOR_HEADER that also need explicit registry-quality sigs
        # (added to _PYTHON_ONLY_METHODS to stop the registry loop re-emitting them,
        # so we provide them here with proper _int/_float aliases).
        "    def reshape(self, *shape: _int | Sequence[_int]) -> Tensor: ...",
        "    def permute(self, *dims: _int | Sequence[_int]) -> Tensor: ...",
        "    def expand(self, *sizes: _int | Sequence[_int]) -> Tensor: ...",
        "    def diagonal(self, offset: _int = 0, dim1: _int = 0, dim2: _int = 1) -> Tensor: ...",
        "    def swapaxes(self, axis0: _int, axis1: _int) -> Tensor: ...",
        "    def broadcast_to(self, shape: Sequence[_int]) -> Tensor: ...",
        "    def unbind(self, axis: _int = 0) -> tuple[Tensor, ...]: ...",
        "    def rsqrt(self) -> Tensor: ...",
    ]

    content = _TENSOR_HEADER + "\n".join(lines) + "\n\n"
    content += "    # ── Python-level overrides (_methods.py) ───────────────────────\n"
    content += "\n".join(python_only) + "\n"
    return content, count


# ── 3. __init__.pyi ───────────────────────────────────────────────────────────

_INIT_HEADER = """\
# --------------------------------------------------------------------- #
# __init__.pyi — auto-generated by tools/gen_pyi.py
# DO NOT EDIT — regenerate with:  python tools/gen_pyi.py
# --------------------------------------------------------------------- #
# fmt: off

from contextlib import AbstractContextManager
from typing import Sequence
import builtins

_float = builtins.float
_int = builtins.int
_bool = builtins.bool

import numpy as np

# ``X as X`` is the PEP 484 explicit-re-export form — without the alias,
# strict-mode type checkers (pyright, mypy ``--no-implicit-reexport``) treat
# these as private imports and IDEs miss ``lucid.Tensor`` autocompletion.
from lucid._C import engine as _C_engine
from lucid._dtype import dtype as dtype
from lucid._device import device as device
from lucid._tensor.tensor import Tensor as Tensor

# Public-facing type aliases (``lucid.Scalar``, ``lucid.TensorLike`` ...).
# These are loaded lazily at runtime via ``__getattr__`` but the .pyi has to
# advertise them up-front for pyright / mypy to accept ``lucid.X`` references.
from lucid._types import (
    Scalar as Scalar,
    TensorLike as TensorLike,
    DeviceLike as DeviceLike,
    DTypeLike as DTypeLike,
    DimLike as DimLike,
    ShapeLike as ShapeLike,
    StateDict as StateDict,
    TensorOrScalar as TensorOrScalar,
    HasShape as HasShape,
    SupportsNumpyConversion as SupportsNumpyConversion,
    SupportsGrad as SupportsGrad,
    TensorLikeProtocol as TensorLikeProtocol,
)

# ── Package metadata ──────────────────────────────────────────────────────────
__version__: str

# ── Dtype objects ─────────────────────────────────────────────────────────────
class float16(dtype): ...
class float32(dtype): ...
class float64(dtype): ...
class bfloat16(dtype): ...
class int8(dtype): ...
class int16(dtype): ...
class int32(dtype): ...
class int64(dtype): ...
class bool_(dtype): ...
class complex64(dtype): ...

half = float16
double = float64
short = int16
long = int64

float = float32
int = int32
bool = bool_

# ── Device ────────────────────────────────────────────────────────────────────
# (re-export from lucid._device)

# ── Global defaults ───────────────────────────────────────────────────────────
def set_default_dtype(dt: dtype) -> None: ...
def get_default_dtype() -> dtype: ...
def set_default_device(dev: device | str) -> None: ...
def get_default_device() -> device: ...

# ── Gradient control ──────────────────────────────────────────────────────────
def no_grad() -> AbstractContextManager[None]: ...
def enable_grad() -> AbstractContextManager[None]: ...
def inference_mode() -> AbstractContextManager[None]: ...
def is_grad_enabled() -> _bool: ...
def set_grad_enabled(mode: _bool) -> None: ...

# ── Serialization ─────────────────────────────────────────────────────────────
def save(obj: object, path: str) -> None: ...
def load(path: str, weights_only: _bool = True) -> object: ...
def save_safetensors(
    state_dict: dict[str, Tensor],
    path: str,
    *,
    metadata: dict[str, str] | None = None,
) -> None: ...
def load_safetensors(
    path: str,
    *,
    device: str = "cpu",
) -> dict[str, object]: ...

# ── Subpackages ───────────────────────────────────────────────────────────────
from lucid import nn as nn
from lucid import optim as optim
from lucid import autograd as autograd
from lucid import linalg as linalg
from lucid import utils as utils
from lucid import amp as amp
from lucid import profiler as profiler
from lucid import einops as einops
from lucid import metal as metal
from lucid import backends as backends
from lucid import test as test
from lucid import dtypes as dtypes

# ── Type predicates ───────────────────────────────────────────────────────────
def is_tensor(obj: object) -> _bool: ...
def is_floating_point(t: Tensor) -> _bool: ...
def is_complex(t: Tensor) -> _bool: ...
def is_signed(t: Tensor) -> _bool: ...

# ── Tensor constructors (lucid.tensor / as_tensor / from_numpy) ──────────────
def tensor(
    data: object,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def as_tensor(
    data: object,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
) -> Tensor: ...
def from_numpy(arr: np.ndarray) -> Tensor: ...

# ── Tensor factories — deterministic (creation.py) ───────────────────────
def zeros(
    *size: _int | tuple[_int, ...],
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def ones(
    *size: _int | tuple[_int, ...],
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def empty(
    *size: _int | tuple[_int, ...],
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def full(
    size: _int | list[_int] | tuple[_int, ...],
    fill_value: _float,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def eye(
    n: _int,
    m: _int | None = None,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def arange(
    start: _float,
    end: _float | None = None,
    step: _float = 1,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
) -> Tensor: ...
def linspace(
    start: _float,
    end: _float,
    steps: _int,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
) -> Tensor: ...
def zeros_like(
    t: Tensor,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def ones_like(
    t: Tensor,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def empty_like(
    t: Tensor,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def full_like(
    t: Tensor, fill_value: _float, *, dtype: DTypeLike = None, device: DeviceLike = None
) -> Tensor: ...
def logspace(
    start: _float,
    end: _float,
    steps: _int,
    base: _float = 10.0,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
) -> Tensor: ...

# ── Tensor factories — random (random.py) ───────────────────────────────
def manual_seed(seed: _int) -> None: ...
def rand(
    *size: _int | tuple[_int, ...],
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
    generator: _C_engine.Generator | None = None,
) -> Tensor: ...
def randn(
    *size: _int | tuple[_int, ...],
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
    generator: _C_engine.Generator | None = None,
) -> Tensor: ...
def randint(
    low: _int,
    high: _int,
    size: list[_int] | tuple[_int, ...],
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
    generator: _C_engine.Generator | None = None,
) -> Tensor: ...
def bernoulli(
    p: _float,
    *,
    size: list[_int] | tuple[_int, ...] | None = None,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
    generator: _C_engine.Generator | None = None,
) -> Tensor: ...
def normal(
    mean: _float = 0.0,
    std: _float = 1.0,
    *,
    size: list[_int] | tuple[_int, ...],
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
    generator: _C_engine.Generator | None = None,
) -> Tensor: ...
def rand_like(
    t: Tensor,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...
def randn_like(
    t: Tensor,
    *,
    dtype: DTypeLike = None,
    device: DeviceLike = None,
    requires_grad: _bool = False,
) -> Tensor: ...

# ── Math ops (registry-generated) ───────────────────────────────────────
"""


def _format_with_docstring(
    sig_line: str, fn_name: str, doc_map: dict[str, tuple[str, bool]]
) -> str:
    """Attach a preserved docstring (if any) to a ``def foo(...) -> R: ...`` line.

    If ``doc_map`` has an entry for ``fn_name``, emit the multi-line form:

        def foo(...) -> R:
            r\"\"\"...preserved docstring...\"\"\"
            ...

    Otherwise return the single-line form unchanged.  ``doc_map`` values are
    ``(docstring_text, is_raw_string)`` tuples — when ``is_raw_string=True``
    the docstring is emitted with the ``r`` prefix so LaTeX backslashes
    survive.
    """
    if fn_name not in doc_map:
        return sig_line
    doc_text, is_raw = doc_map[fn_name]
    # sig_line ends with ': ...'; strip the trailing ' ...' and add body.
    if sig_line.endswith(": ..."):
        head = sig_line[:-4]  # keep the colon
    else:
        head = sig_line
    indent = "    "
    prefix = "r" if is_raw else ""
    # Re-indent the docstring body
    body_lines = [indent + l for l in doc_text.split("\n")]
    body = "\n".join(body_lines)
    return f'{head}\n{indent}{prefix}"""{body}\n{indent}"""\n{indent}...'


def _load_existing_docstrings(path) -> dict[str, tuple[str, bool]]:
    """Parse an existing ``.pyi`` file and return ``{fn_name: (doc, is_raw)}``.

    Preserves manually-written docstrings across regenerations of the stub.
    Detects raw-string prefixes by re-scanning the source text (AST loses
    that information).
    """
    import ast as _ast
    import re as _re

    try:
        src = path.read_text(encoding="utf-8")
    except Exception:
        return {}
    try:
        tree = _ast.parse(src)
    except Exception:
        return {}
    # Map (line of docstring constant) → was-raw-prefixed?
    raw_at_line: dict[int, bool] = {}
    for m in _re.finditer(r'^[ \t]*([rR])?"""', src, _re.MULTILINE):
        # convert byte offset to line number (1-based)
        line = src.count("\n", 0, m.start()) + 1
        raw_at_line[line] = bool(m.group(1))
    out: dict[str, tuple[str, bool]] = {}
    for node in _ast.walk(tree):
        if not isinstance(node, _ast.FunctionDef):
            continue
        doc = _ast.get_docstring(node)
        if not doc:
            continue
        # Body's first stmt is the docstring Expr; check its line for raw-ness
        first = node.body[0]
        is_raw = raw_at_line.get(first.lineno, False)
        out[node.name] = (doc, is_raw)
    return out


def _free_fn_sig(entry) -> str:
    """Generate a free function signature for a registry entry.

    Pulls the explicit ``__signature__`` that ``lucid._ops._make_free_fn``
    attaches to every wrapper, so the stub mirrors the runtime surface
    without us having to redo all the parsing here.  Falls back to the
    legacy heuristic only if the wrapper hasn't been built yet (e.g.
    during a partial registry).
    """
    import inspect as _inspect

    name = entry.free_fn_name or entry.name

    # Live-introspect the actual wrapper.  This includes Tensor unwrapping
    # signatures + any param renames done in ``_rename_leading_tensor_params``.
    try:
        from lucid._ops import _make_free_fn

        wrapper = _make_free_fn(name)
        sig = _inspect.signature(wrapper)
    except Exception:
        sig = None

    if sig is not None:
        parts = []
        for pname, param in sig.parameters.items():
            kind = param.kind
            ann = _annotation_for_param(pname, param.annotation, entry, kind)
            ann_str = f": {ann}" if ann else ""
            if kind == _inspect.Parameter.VAR_POSITIONAL:
                parts.append(f"*{pname}{ann_str}")
            elif kind == _inspect.Parameter.VAR_KEYWORD:
                parts.append(f"**{pname}{ann_str}")
            elif kind == _inspect.Parameter.KEYWORD_ONLY:
                # Suppress redundant ``*`` if a VAR_POSITIONAL ``*xxx`` is
                # already present — Python's grammar disallows two ``*``
                # markers in one signature.
                if not any(p == "*" for p in parts) and not any(
                    p.startswith("*") and not p.startswith("**") for p in parts
                ):
                    parts.append("*")
                if param.default is _inspect.Parameter.empty:
                    parts.append(f"{pname}{ann_str}")
                else:
                    parts.append(f"{pname}{ann_str} = ...")
            else:  # POSITIONAL_OR_KEYWORD / POSITIONAL_ONLY
                if param.default is _inspect.Parameter.empty:
                    parts.append(f"{pname}{ann_str}")
                else:
                    parts.append(f"{pname}{ann_str} = ...")
        return f"def {name}({', '.join(parts)}) -> Tensor: ..."

    # Fallback (shouldn't trigger in normal builds): legacy heuristic.
    n = entry.n_tensor_args
    if n == -1:
        return f"def {name}(tensors: list[Tensor], *args: object) -> Tensor: ..."
    parts = []
    if n >= 1:
        parts.append("input: Tensor")
    if n >= 2:
        parts.append("other: Tensor | float")
    if entry.extra_kwargs:
        parts.append("*args: Any")
        parts.append("**kwargs: Any")
    return f"def {name}({', '.join(parts)}) -> Tensor: ..."


# Canonical type for every parameter name we expect to see across the
# registry / composite / alias layers.  Drives both ``_annotation_for_param``
# (for wrappers without source annotations) and ``_simplify_annotation``'s
# fallback (for parameters whose runtime annotation is ``empty``).
#
# Every name here MUST resolve to a concrete type — ``Any`` is forbidden by
# project policy.  When in doubt, prefer ``object`` (catch-all opaque) over
# ``Any`` so type checkers still narrow at use sites.
_PARAM_TYPE_MAP: dict[str, str] = {
    # ── tensors (all forms) ─────────────────────────────────────────────────
    "input": "Tensor",
    "other": "Tensor | Scalar",
    "cond": "Tensor",
    "x": "Tensor",
    "y": "Tensor",
    "a": "Tensor",
    "b": "Tensor",
    "tensor": "Tensor",
    "tensors": "list[Tensor]",
    "arrays": "list[Tensor]",
    "indices": "Tensor",
    "index": "Tensor",
    "mask": "Tensor",
    "src": "Tensor",
    "source": "Tensor",
    "base": "Tensor",
    "elements": "Tensor",
    "test_elements": "Tensor",
    "exponent": "Tensor | Scalar",
    "weight": "Tensor",
    "self": "Tensor",
    # ── dim-style (single int, never None) ─────────────────────────────────
    "dim1": "int",
    "dim2": "int",
    "dim0": "int",
    "axis0": "int",
    "axis1": "int",
    "axis2": "int",
    "start_dim": "int",
    "end_dim": "int",
    "start_axis": "int",
    "end_axis": "int",
    # ── dim (accepts int / list[int] / None) ───────────────────────────────
    "dim": "DimLike",
    "dims": "Sequence[int]",
    # ── shape-like ─────────────────────────────────────────────────────────
    "shape": "ShapeLike",
    "size": "ShapeLike",
    "new_shape": "ShapeLike",
    "perm": "Sequence[int]",
    "reps": "Sequence[int]",
    "repeats": "int | Sequence[int]",
    "shifts": "int | Sequence[int]",
    "padding": "Sequence[int] | Sequence[tuple[int, int]]",
    "pad_width": "Sequence[tuple[int, int]]",
    # ── scalars / numerics ─────────────────────────────────────────────────
    "value": "Scalar",
    "fill_value": "Scalar",
    "scalar": "Scalar",
    "constant": "Scalar",
    "min": "Scalar | None",
    "max": "Scalar | None",
    "k": "int",
    "n": "int",
    "N": "int",
    "m": "int",
    "M": "int",
    "offset": "int",
    "chunks": "int",
    "num_splits": "int",
    "split_size_or_sections": "int | Sequence[int]",
    "bins": "int",
    "bins_a": "int",
    "bins_b": "int",
    "lo": "float",
    "hi": "float",
    "lo_a": "float",
    "hi_a": "float",
    "lo_b": "float",
    "hi_b": "float",
    "ranges": "Sequence[tuple[float, float]]",
    "step": "float",
    "start": "_int",
    "end": "_int",
    "steps": "int",
    "p": "float",
    "ord": "int | float | str",
    "eps": "float",
    "alpha": "float",
    "beta": "float",
    "gamma": "float",
    "slope": "float",
    "lambd": "float",
    "scale": "float",
    "tau": "float",
    "rtol": "float",
    "atol": "float",
    "nan": "float | None",
    "posinf": "float | None",
    "neginf": "float | None",
    "rcond": "float | None",
    "tol": "float | None",
    "q": "float | Tensor",
    # ── booleans ───────────────────────────────────────────────────────────
    "keepdim": "bool",
    "keepdims": "bool",
    "unbiased": "bool | None",
    "correction": "int",
    "ddof": "int",
    "upper": "bool",
    "lower": "bool",
    "training": "bool",
    "inplace": "bool",
    "include_self": "bool",
    "invert": "bool",
    "return_inverse": "bool",
    "return_counts": "bool",
    "right": "bool",
    "sorted": "bool",
    "largest": "bool",
    "stable": "bool",
    "density": "bool",
    "replacement": "bool",
    "increasing": "bool",
    "exclusive": "bool",
    "hermitian": "bool",
    "antialias": "bool",
    "align_corners": "bool",
    "recompute_scale_factor": "bool",
    "with_replacement": "bool",
    "complex_output": "bool",
    "ceil_mode": "bool",
    "count_include_pad": "bool",
    "return_indices": "bool",
    "requires_grad": "bool",
    "as_tuple": "bool",
    # ── strings ────────────────────────────────────────────────────────────
    "mode": "str",
    "norm": "str | None",
    "indexing": "str",
    "indexing_xy": "bool",
    "reduce": "str | None",
    "reduction": "str",
    "driver": "str | None",
    "kind": "str",
    "interpolation": "str",
    "padding_mode": "str",
    "name": "str",
    "path": "str",
    "format": "str",
    # ── dtype / device / generator ─────────────────────────────────────────
    "dtype": "DTypeLike",
    "device": "DeviceLike",
    "generator": "_C_engine.Generator | None",
    "rng": "_C_engine.Generator | None",
    "out_dtype": "DTypeLike",
    "a_dtype": "DTypeLike",
    "b_dtype": "DTypeLike",
    # ── data / opaque ──────────────────────────────────────────────────────
    "data": "object",
    "obj": "object",
    "arr": "np.ndarray",
    "ndarray": "np.ndarray",
    "destination": "int | str",
    # ── fft-specific ───────────────────────────────────────────────────────
    "s": "Sequence[int] | None",
    # ── linalg-specific ────────────────────────────────────────────────────
    "A": "Tensor",
    "B": "Tensor",
    "LU": "Tensor",
    "pivots": "Tensor",
    "H": "Tensor",
    "UPLO": "str",
    "full_matrices": "bool",
    "compute_uv": "bool",
    "left": "bool",
    "unitriangular": "bool",
    "num_samples": "int",
}


def _annotation_for_param(name: str, ann, entry, kind) -> str:
    """Pick a stub-friendly annotation for a wrapper parameter.

    The runtime ``__signature__`` rarely carries annotations (most wrappers
    inherit from a body with bare names), so we infer from the parameter
    name via ``_PARAM_TYPE_MAP``.  Honours an explicit annotation if one
    *is* present (adapters with proper signatures).
    """
    import inspect as _inspect

    if ann is not _inspect.Parameter.empty:
        return _stringify_annotation(ann)

    n = entry.n_tensor_args

    # ``*shape`` / ``*sizes`` / ``*dims`` variadic — single ints.
    if kind == _inspect.Parameter.VAR_POSITIONAL:
        if name in {"shape", "sizes", "size", "dims"}:
            return "int"
        return "object"

    # List-style ops: the first slot is the tensor list.
    if n == -1 and name == "tensors":
        return "list[Tensor]"

    if name in _PARAM_TYPE_MAP:
        return _PARAM_TYPE_MAP[name]

    # Final guard — never emit ``Any``.  Unknown role → opaque ``object``.
    return "object"


def _stringify_annotation(ann) -> str:
    """Convert a runtime annotation to a stub-friendly string."""
    import re as _re
    import typing as _typing

    # ForwardRef instances stringify with their evaluation owner (whose
    # address rotates every interpreter run) — collapse to the bare name.
    if isinstance(ann, _typing.ForwardRef):
        return ann.__forward_arg__

    raw = repr(ann) if not isinstance(ann, str) else ann
    raw = raw.replace("<class '", "").replace("'>", "")
    raw = raw.replace("typing.", "")
    raw = raw.replace("lucid._tensor.tensor.Tensor", "Tensor")
    raw = raw.replace("lucid._C.engine.TensorImpl", "Tensor")
    raw = raw.replace("lucid._C._engine.TensorImpl", "Tensor")
    raw = raw.replace("lucid._dtype.dtype", "dtype")
    raw = raw.replace("lucid._device.device", "device")
    raw = raw.replace("_DType", "dtype")
    raw = raw.replace("NoneType", "None")
    # Strip the ``ForwardRef('Name', owner=<function … at 0xADDR>)``
    # debug repr that leaks into stubs when ``Format.FORWARDREF`` parses an
    # adapter's TYPE_CHECKING annotation.  Keep only the name inside quotes.
    raw = _re.sub(
        r"ForwardRef\(\s*'([^']+)'(?:\s*,[^)]*)?\)",
        r"\1",
        raw,
    )
    # The literal string ``Any`` is forbidden in this codebase's stubs —
    # replace with ``object`` if it sneaks in via a dependency type repr.
    raw = raw.replace(" Any ", " object ").replace("[Any]", "[object]")
    if raw.strip() == "Any":
        raw = "object"
    return raw


def _sig_from_callable(name: str, fn: object) -> str:
    """Generate a stub line from a live callable via AST source parsing.

    Python 3.14 evaluates annotations lazily (PEP 649): accessing
    ``__annotations__`` or calling ``inspect.signature()`` on a function
    whose annotations reference TYPE_CHECKING-only names raises
    ``NameError``.  We therefore parse the *source text* via ``ast`` —
    which never evaluates anything — and emit annotation strings verbatim.

    Falls back to a name-inferred signature (using ``_PARAM_TYPE_MAP``)
    when source is unavailable (built-ins, C extensions, lambdas).  Never
    emits ``*args`` / ``**kwargs`` — these are forbidden in stubs (H9).
    """
    import ast
    import inspect
    import textwrap

    # ── Try AST-based extraction (preferred, annotation-safe) ────────────
    try:
        raw_src = inspect.getsource(fn)
        src = textwrap.dedent(raw_src)
        tree = ast.parse(src)
    except Exception:
        tree = None

    if tree is not None:
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if node.name != name:
                continue
            return _sig_from_ast(name, node)

    # ── Fallback: code-object introspection (no annotation evaluation) ───
    code = getattr(fn, "__code__", None)
    if code is None:
        # Absolute last resort for built-ins / C callables.
        return f"def {name}(input: Tensor, /) -> Tensor: ..."

    n_all = code.co_argcount
    n_posonly = code.co_posonlyargcount
    n_kwonly = code.co_kwonlyargcount
    has_varargs = bool(code.co_flags & 0x04)
    has_varkw = bool(code.co_flags & 0x08)

    all_names = code.co_varnames
    pos_kw_names = list(all_names[:n_all])
    kwonly_start = n_all + (1 if has_varargs else 0)
    kwonly_names = list(all_names[kwonly_start : kwonly_start + n_kwonly])

    defaults: tuple[object, ...] = getattr(fn, "__defaults__", None) or ()
    kwdefaults: dict[str, object] = getattr(fn, "__kwdefaults__", None) or {}

    parts: list[str] = []
    default_offset = n_all - len(defaults)

    for i, pname in enumerate(pos_kw_names[:n_posonly]):
        ptype = _PARAM_TYPE_MAP.get(pname, "object")
        sfx = " = ..." if i >= default_offset else ""
        parts.append(f"{pname}: {ptype}{sfx}")
    if n_posonly:
        parts.append("/")
    for i, pname in enumerate(pos_kw_names[n_posonly:], n_posonly):
        ptype = _PARAM_TYPE_MAP.get(pname, "object")
        sfx = " = ..." if i >= default_offset else ""
        parts.append(f"{pname}: {ptype}{sfx}")

    # *args are genuinely variadic only if the source truly has them; the
    # fallback code-object path treats them as unknown — skip (H9).
    if has_varargs and not has_varkw and not kwonly_names:
        varargs_name = all_names[n_all]
        ptype = _PARAM_TYPE_MAP.get(varargs_name, "object")
        parts.append(f"*{varargs_name}: {ptype}")
    elif kwonly_names:
        parts.append("*")

    for pname in kwonly_names:
        ptype = _PARAM_TYPE_MAP.get(pname, "object")
        sfx = " = ..." if pname in kwdefaults else ""
        parts.append(f"{pname}: {ptype}{sfx}")

    # **kwargs: skip entirely per H9 (fallback path only).

    ret = _RETURN_TYPE_MAP.get(name, "Tensor")
    return f"def {name}({', '.join(parts)}) -> {ret}: ..."


# Return-type override map for composite ops that don't return Tensor.
_RETURN_TYPE_MAP: dict[str, str] = {
    "allclose": "bool",
    "is_conj": "bool",
    "is_neg": "bool",
    "is_nonzero": "bool",
    "is_same_size": "bool",
    "is_storage": "bool",
    "can_cast": "bool",
    "numel": "int",
    "result_type": "DTypeLike",
    "std_mean": "tuple[Tensor, Tensor]",
    "var_mean": "tuple[Tensor, Tensor]",
    "frexp": "tuple[Tensor, Tensor]",
    "histogram": "tuple[Tensor, Tensor]",
    "histogram2d": "tuple[Tensor, Tensor, Tensor]",
    "histogramdd": "tuple[Tensor, list[Tensor]]",
    "atleast_1d": "Tensor | tuple[Tensor, ...]",
    "atleast_2d": "Tensor | tuple[Tensor, ...]",
    "atleast_3d": "Tensor | tuple[Tensor, ...]",
    "dsplit": "list[Tensor]",
    "hsplit": "list[Tensor]",
    "vsplit": "list[Tensor]",
    "tensor_split": "list[Tensor]",
    "column_stack": "Tensor",
    "row_stack": "Tensor",
    "dstack": "Tensor",
    "diff": "Tensor",
    "lerp": "Tensor",
}


def _sig_from_ast(name: str, node: "ast.FunctionDef | ast.AsyncFunctionDef") -> str:  # type: ignore[name-defined]
    """Emit a stub line from a parsed AST ``FunctionDef`` node.

    Annotation nodes are converted to strings via ``ast.unparse`` (never
    evaluated), so TYPE_CHECKING-only names work without triggering
    ``NameError``.  Positional-only and keyword-only markers are preserved.
    ``*args`` / ``**kwargs`` are omitted per H9 unless the parameter name
    implies genuine variadic intent (e.g. ``*tensors``).
    """
    import ast

    args = node.args

    def _ann(ann_node: "ast.expr | None") -> str:
        if ann_node is None:
            return ""
        return ast.unparse(ann_node)

    parts: list[str] = []

    # Positional-only (before the ``/`` marker)
    n_posonly = len(args.posonlyargs)
    all_pos = list(args.posonlyargs) + list(args.args)
    n_pos_kw = len(args.args)
    n_all = n_posonly + n_pos_kw
    n_defaults = len(args.defaults)
    default_offset = n_all - n_defaults

    for i, arg in enumerate(all_pos):
        ann = _ann(arg.annotation)
        ptype = ann if ann else _PARAM_TYPE_MAP.get(arg.arg, "object")
        sfx = " = ..." if i >= default_offset else ""
        parts.append(f"{arg.arg}: {ptype}{sfx}")
    if n_posonly:
        parts.append("/")

    # *args — only emit when genuinely variadic (e.g. ``*tensors: Tensor``).
    # Per H9: ``*args: object`` is never emitted.
    if args.vararg:
        vname = args.vararg.arg
        ann = _ann(args.vararg.annotation)
        ptype = ann if ann else _PARAM_TYPE_MAP.get(vname, "object")
        # Emit only when the annotation or name is Tensor-typed (truly variadic).
        if ptype not in {"object", "Any"}:
            parts.append(f"*{vname}: {ptype}")
        elif args.kwonlyargs:
            parts.append("*")
    elif args.kwonlyargs:
        parts.append("*")

    # Keyword-only args
    kw_defaults = args.kw_defaults  # list of default AST nodes (None = no default)
    for i, arg in enumerate(args.kwonlyargs):
        ann = _ann(arg.annotation)
        ptype = ann if ann else _PARAM_TYPE_MAP.get(arg.arg, "object")
        sfx = " = ..." if kw_defaults[i] is not None else ""
        parts.append(f"{arg.arg}: {ptype}{sfx}")

    # **kwargs — H9: omit entirely.

    # Return type
    ret = _ann(node.returns) if node.returns else _RETURN_TYPE_MAP.get(name, "Tensor")

    return f"def {name}({', '.join(parts)}) -> {ret}: ..."


def _inferred_param_type(name: str, kind) -> str:
    """Stub annotation for a parameter whose runtime annotation is empty.

    Mirrors ``_annotation_for_param`` but without an OpEntry — used by the
    composite / alias paths in ``gen_init_pyi``.
    """
    import inspect as _inspect

    if kind == _inspect.Parameter.VAR_POSITIONAL:
        if name in {"shape", "sizes", "size", "dims"}:
            return "int"
        return "object"
    if kind == _inspect.Parameter.VAR_KEYWORD:
        return "object"
    return _PARAM_TYPE_MAP.get(name, "object")


def _simplify_annotation(ann: object) -> str:
    """Convert a runtime annotation object to a terse string for stubs."""
    import inspect

    if ann is inspect.Parameter.empty:
        return "Any"
    raw = str(ann)
    # Strip module prefixes that would be unknown inside the stub.
    raw = raw.replace("<class '", "").replace("'>", "")
    raw = raw.replace("typing.", "").replace("lucid._tensor.tensor.", "")
    raw = raw.replace("lucid._dtype.", "").replace("lucid._device.", "")
    # Collapse common generics to something valid in stubs.
    raw = raw.replace("NoneType", "None")
    return raw


def gen_init_pyi() -> tuple[str, int]:
    import inspect
    from lucid._ops._registry import _REGISTRY

    # Preserve any manually-written docstrings in the existing __init__.pyi.
    # Without this, each regeneration would wipe out hand-crafted NumPy-style
    # docstrings that the docs site (web/) relies on for the lucid.ops /
    # lucid.creation / lucid.ops.composite pages.
    _existing_docs = _load_existing_docstrings(ROOT / "lucid/__init__.pyi")

    # Names whose signatures are hand-crafted in the ``overrides`` list below.
    # Exclude them from the registry loop so the correct stub wins (registry
    # introspection yields pybind11 TensorImpl signatures, not Tensor).
    _OVERRIDE_NAMES: frozenset[str] = frozenset(
        {
            "sum",
            "mean",
            "prod",
            "max",
            "min",
            "var",
            "std",
            "argmax",
            "argmin",
            "squeeze",
            "repeat",
            "repeat_interleave",
            "split",
            "tensordot",
            "meshgrid",
        }
    )

    seen: set[str] = set()
    lines = []
    count = 0
    for entry in _REGISTRY:
        fn = entry.free_fn_name
        if fn is None or fn in seen or fn in _OVERRIDE_NAMES:
            continue
        seen.add(fn)
        lines.append(_format_with_docstring(_free_fn_sig(entry), fn, _existing_docs))
        count += 1

    # Also include reference-compatible overrides defined directly in _ops/__init__.py.
    # Uses _int / _bool aliases (defined at top of _INIT_HEADER) to avoid shadowing
    # by lucid's own int / bool dtype aliases.
    overrides = [
        "def sum(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False, *, correction: _int = 1) -> Tensor: ...",
        "def mean(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False) -> Tensor: ...",
        "def prod(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False) -> Tensor: ...",
        "def max(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False) -> Tensor: ...",
        "def min(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False) -> Tensor: ...",
        "def var(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False, *, correction: _int = 1) -> Tensor: ...",
        "def std(x: Tensor, dim: _int | list[_int] | None = None, keepdim: _bool = False, *, correction: _int = 1) -> Tensor: ...",
        "def argmax(x: Tensor, dim: _int | None = None, keepdim: _bool = False) -> Tensor: ...",
        "def argmin(x: Tensor, dim: _int | None = None, keepdim: _bool = False) -> Tensor: ...",
        "def squeeze(x: Tensor, dim: _int | list[_int] | None = None) -> Tensor: ...",
        "def repeat(x: Tensor, repeats: _int, dim: _int | None = None) -> Tensor: ...",
        "def repeat_interleave(x: Tensor, repeats: _int, dim: _int | None = None) -> Tensor: ...",
        "def split(x: Tensor, split_size_or_sections: _int | list[_int], dim: _int = 0) -> list[Tensor]: ...",
        "def tensordot(a: Tensor, b: Tensor, dims: _int | list[list[_int]] = 2) -> Tensor: ...",
        "def meshgrid(*tensors: Tensor, indexing: str = 'ij') -> list[Tensor]: ...",
    ]

    # ── Composite ops (lucid._ops.composite) ─────────────────────────────────
    import lucid._ops.composite as _comp
    from lucid._ops.composite import COMPOSITE_NAMES

    composite_lines = [
        "\n# ── Constants ────────────────────────────────────────────────────────",
        "pi: float",
        "e: float",
        "inf: float",
        "nan: float",
        "newaxis: None",
        "\n# ── Composite ops (elementwise / shape / blas / reductions / predicates / dtype) ─",
    ]
    _CONSTANT_NAMES = {"pi", "e", "inf", "nan", "newaxis"}
    for n in sorted(COMPOSITE_NAMES - _CONSTANT_NAMES):
        if n in seen:
            continue
        fn = getattr(_comp, n, None)
        if fn is None or not callable(fn):
            continue
        seen.add(n)
        composite_lines.append(
            _format_with_docstring(_sig_from_callable(n, fn), n, _existing_docs)
        )

    # ── nn.functional / linalg / method aliases ───────────────────────────────
    import lucid

    alias_groups = {
        "Tensor-method aliases": lucid._METHOD_ALIASES,  # type: ignore[attr-defined]
    }
    alias_lines = []
    for group_label, name_set in alias_groups.items():
        group: list[str] = []
        for n in sorted(name_set):
            if n in seen:
                continue
            fn = getattr(lucid, n, None)
            if fn is None:
                continue
            seen.add(n)
            group.append(
                _format_with_docstring(_sig_from_callable(n, fn), n, _existing_docs)
            )
        if group:
            alias_lines.append(f"\n# ── {group_label} ─────────────────")
            alias_lines.extend(group)

    # Attach preserved docstrings to the hand-crafted overrides too (sum,
    # mean, prod, var, std, argmax, argmin, squeeze, repeat, split, ...).
    overrides = [
        _format_with_docstring(
            line, line.split("(")[0].removeprefix("def ").strip(), _existing_docs
        )
        for line in overrides
    ]

    content = _INIT_HEADER + "\n".join(lines) + "\n\n"
    content += (
        "# ── Reference-compatible overrides (see _ops/__init__.py) ───────────\n"
    )
    content += "\n".join(overrides) + "\n"
    content += "\n".join(composite_lines) + "\n"
    content += "\n".join(alias_lines) + "\n"
    # _DType is a private alias (= dtype) used in source annotations but not
    # exported in __init__.pyi — replace with the public ``dtype`` name.
    content = content.replace("_DType", "dtype")

    total = count + len(
        [l for l in composite_lines + alias_lines if l.startswith("def ")]
    )
    return content, total


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    engine_content, n_engine = gen_engine_pyi()
    tensor_content, n_tensor_methods = gen_tensor_pyi()
    init_content, n_free_fns = gen_init_pyi()

    engine_path = ROOT / "lucid/_C/engine.pyi"
    tensor_path = ROOT / "lucid/_tensor/tensor.pyi"
    init_path = ROOT / "lucid/__init__.pyi"

    _write(engine_path, engine_content)
    _write(tensor_path, tensor_content)
    _write(init_path, init_content)

    print(
        f"[gen_pyi] engine.pyi  → {engine_path.relative_to(ROOT)}  ({n_engine} schemas)"
    )
    print(
        f"[gen_pyi] tensor.pyi  → {tensor_path.relative_to(ROOT)}  ({n_tensor_methods} registry)"
    )
    print(
        f"[gen_pyi] __init__.pyi → {init_path.relative_to(ROOT)}  ({n_free_fns} registry fns)"
    )
    print("[gen_pyi] done.")


if __name__ == "__main__":
    main()
