#!/usr/bin/env python3
"""Phase 6.3 — Schema-driven op reference docs generator.

Reads lucid._C.engine at runtime and emits a Markdown reference page at
``docs/source/api/ops.md`` (or --out path).

Sections:
  - Ops by AmpPolicy (Promote / KeepInput / ForceFP32)
  - Non-deterministic ops with their determinism notes
  - Full alphabetical table

Usage:
    python tools/gen_op_reference.py [--out PATH]
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from lucid._C import engine as E  # noqa: E402


def _sig(fn) -> str:
    try:
        return str(inspect.signature(fn))
    except (ValueError, TypeError):
        return "(*args, **kwargs)"


def generate(out_path: Path) -> None:
    schemas = {s.name: s for s in E.op_registry_all()}
    total = len(schemas)

    # Group by policy
    promote, keep_input, force_fp32, nondeterministic = [], [], [], []
    for name, s in sorted(schemas.items()):
        if s.amp_policy == E.AmpPolicy.Promote:
            promote.append(s)
        elif s.amp_policy == E.AmpPolicy.KeepInput:
            keep_input.append(s)
        else:
            force_fp32.append(s)
        if not s.deterministic:
            nondeterministic.append(s)

    lines = [
        "<!-- Auto-generated by tools/gen_op_reference.py — DO NOT EDIT -->",
        "",
        "# Op Reference",
        "",
        f"> **{total} ops** registered in the engine.  ",
        "> Regenerate: `python tools/gen_op_reference.py`",
        "",
    ]

    def _section(title: str, schemas_list: list, note: str = "") -> None:
        lines.append(f"## {title}")
        lines.append("")
        if note:
            lines.append(f"_{note}_")
            lines.append("")
        lines.append("| Op | Sig | Det | Note |")
        lines.append("|---|---|:---:|---|")
        for s in schemas_list:
            fn = getattr(E, s.name, None)
            sig = _sig(fn).replace("|", "\\|") if fn else "—"
            det = "✅" if s.deterministic else "⚠️"
            note_col = s.determinism_note if not s.deterministic else ""
            lines.append(f"| `{s.name}` | `{s.name}{sig}` | {det} | {note_col} |")
        lines.append("")

    _section(
        f"Promote ({len(promote)} ops)",
        promote,
        "Under F16 autocast: outputs F16 on GPU, stays F32 on CPU (no F16 ops in Accelerate).",
    )
    _section(
        f"KeepInput ({len(keep_input)} ops)",
        keep_input,
        "Output dtype always equals input dtype — autocast is ignored.",
    )
    _section(
        f"ForceFP32 ({len(force_fp32)} ops)",
        force_fp32,
        "Always executes in F32 even under F16 autocast (precision-sensitive ops).",
    )

    if nondeterministic:
        lines.append("## Non-deterministic ops")
        lines.append("")
        lines.append("These ops require an explicit `Generator` under `set_deterministic(True)`.")
        lines.append("")
        lines.append("| Op | Reason |")
        lines.append("|---|---|")
        for s in nondeterministic:
            lines.append(f"| `{s.name}` | {s.determinism_note} |")
        lines.append("")

    content = "\n".join(lines)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"[gen_op_reference] wrote {out_path}  ({total} ops, "
          f"{len(content.splitlines())} lines)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=str(ROOT / "docs" / "source" / "api" / "ops.md"),
        help="Output path for the ops reference.",
    )
    args = parser.parse_args()
    generate(Path(args.out))


if __name__ == "__main__":
    main()
