#!/usr/bin/env python3
"""
tools/new_op.py — Lucid op scaffolding CLI.

Generates all boilerplate for a new engine-backed op so that the developer
only has to fill in the gradient formula and backend kernel.

Usage:
  python tools/new_op.py <name> [options]

  <name>   snake_case op name as it will appear in Python  (e.g. softclamp)

Options:
  --kind        unary | binary | composite   (default: unary)
  --save-input  save forward inputs  for backward  (unary/binary)
  --save-output save forward output  for backward  (unary only)
  --amp         keep | promote | fp32        (default: promote)
  --export      also add to lucid.__all__   (default: _OPS_NAMES only)
  --dry-run     print generated code without modifying any files

Examples:
  python tools/new_op.py softclamp --kind unary --save-input --amp keep
  python tools/new_op.py xlogy     --kind binary
  python tools/new_op.py softmax2d --kind composite
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

# ── paths ─────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent.parent
OPS = ROOT / "lucid" / "_C" / "ops"
BE = ROOT / "lucid" / "_C" / "backend"
BIND = ROOT / "lucid" / "_C" / "bindings"
CMAKE = ROOT / "lucid" / "_C" / "CMakeLists.txt"
INIT = ROOT / "lucid" / "__init__.py"
REGISTRY = ROOT / "lucid" / "_ops" / "_registry.py"


# ── name helpers ──────────────────────────────────────────────────────────────


def to_camel(snake: str) -> str:
    """softclamp → Softclamp   soft_clamp → SoftClamp"""
    return "".join(w.capitalize() for w in snake.split("_"))


def amp_enum(amp: str) -> str:
    return {"keep": "KeepInput", "promote": "Promote", "fp32": "ForceFP32"}[amp]


# ── file helpers ──────────────────────────────────────────────────────────────


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write(path: Path, text: str, dry_run: bool) -> None:
    if dry_run:
        print(f"\n{'─'*60}")
        print(f"Would write: {path.relative_to(ROOT)}")
        print(f"{'─'*60}")
        print(text[:800] + ("..." if len(text) > 800 else ""))
    else:
        path.write_text(text, encoding="utf-8")
        print(f"  ✅  {path.relative_to(ROOT)}")


def insert_after(text: str, anchor: str, insertion: str) -> str:
    """Insert `insertion` immediately after the first occurrence of `anchor`."""
    idx = text.find(anchor)
    if idx == -1:
        raise ValueError(f"Anchor not found: {anchor!r}")
    end = idx + len(anchor)
    return text[:end] + insertion + text[end:]


def insert_before(text: str, anchor: str, insertion: str) -> str:
    """Insert `insertion` immediately before the first occurrence of `anchor`."""
    idx = text.find(anchor)
    if idx == -1:
        raise ValueError(f"Anchor not found: {anchor!r}")
    return text[:idx] + insertion + text[idx:]


# ── UNARY ─────────────────────────────────────────────────────────────────────


def _unary_header(name: str, camel: str, amp: str, si: bool, so: bool) -> str:
    saves_in = str(si).lower()
    saves_out = str(so).lower()
    input_arg = "x" if si else "/*x*/"
    output_arg = "out" if so else "/*out*/"
    return dedent(f"""\
        // lucid/_C/ops/ufunc/{camel}.h
        //
        // Auto-generated by tools/new_op.py  (kind=unary, amp={amp}).
        // Fill in grad_formula / grad_formula_impl before building.

        #pragma once

        #include "../../api.h"
        #include "../../backend/IBackend.h"
        #include "../../core/AmpPolicy.h"
        #include "../../core/OpSchema.h"
        #include "../../core/Storage.h"
        #include "../../core/fwd.h"
        #include "_UnaryOp.h"

        namespace lucid {{

        // Autograd node for element-wise {name}: y = {name}(x).
        class LUCID_API {camel}Backward : public UnaryOp<{camel}Backward> {{
        public:
            static constexpr bool kSavesInput  = {saves_in};   // save forward input x
            static constexpr bool kSavesOutput = {saves_out};  // save forward output y
            static const OpSchema schema_v1;

            static Storage dispatch(backend::IBackend& be, const Storage& a,
                                    const Shape& shape, Dtype dt) {{
                return be.{name}(a, shape, dt);
            }}

            // TODO: implement gradient formula.
            Storage grad_formula(const Storage& g);

            // TODO: implement graph-mode gradient formula.
            TensorImplPtr grad_formula_impl(const TensorImplPtr& g,
                                            const TensorImplPtr& {input_arg},
                                            const TensorImplPtr& {output_arg});
        }};

        LUCID_API TensorImplPtr {name}_op(const TensorImplPtr& a);

        }}  // namespace lucid
        """)


def _unary_cpp(name: str, camel: str, amp: str, si: bool, so: bool) -> str:
    amp_e = amp_enum(amp)
    saved = []
    if si:
        saved.append("saved_inputs_[0] = x")
    if so:
        saved.append("saved_output_ = y")
    saved_doc = ", ".join(saved) if saved else "(nothing saved)"
    input_arg = "x" if si else "/*x*/"
    output_arg = "out" if so else "/*out*/"
    return dedent(f"""\
        // lucid/_C/ops/ufunc/{camel}.cpp
        //
        // Auto-generated by tools/new_op.py. Fill in the TODO sections.

        #include "{camel}.h"

        #include "../../autograd/Helpers.h"
        #include "../../core/OpRegistry.h"

        namespace lucid {{

        const OpSchema {camel}Backward::schema_v1{{"{name}", 1,
                                                    AmpPolicy::{amp_e}, true}};

        // Gradient of {name}.  Available saved tensors: {saved_doc}.
        // TODO: implement.
        Storage {camel}Backward::grad_formula(const Storage& g) {{
            // Example:  return g;                 (identity — replace with formula)
            (void)g;
            throw std::runtime_error("{name} backward: not yet implemented");
        }}

        // Graph-mode gradient (used by the new autograd engine).
        // TODO: implement.
        TensorImplPtr {camel}Backward::grad_formula_impl(
            const TensorImplPtr& g,
            const TensorImplPtr& {input_arg},
            const TensorImplPtr& {output_arg}) {{
            // TODO
            (void)g;
            throw std::runtime_error("{name} grad_formula_impl: not yet implemented");
        }}

        TensorImplPtr {name}_op(const TensorImplPtr& a) {{
            return {camel}Backward::forward(a);
        }}
        LUCID_REGISTER_OP({camel}Backward)

        }}  // namespace lucid
        """)


# ── BINARY ────────────────────────────────────────────────────────────────────


def _binary_header(name: str, camel: str, amp: str, saves: bool) -> str:
    saves_str = str(saves).lower()  # kSavesInputs = true → save inputs for backward
    return dedent(f"""\
        // lucid/_C/ops/bfunc/{camel}.h
        //
        // Auto-generated by tools/new_op.py  (kind=binary, amp={amp}).

        #pragma once

        #include <utility>
        #include "../../api.h"
        #include "../../core/AmpPolicy.h"
        #include "../../core/OpSchema.h"
        #include "../../core/Storage.h"
        #include "../../core/fwd.h"
        #include "_BinaryOp.h"

        namespace lucid {{

        // Autograd node for element-wise {name}: c = {name}(a, b).
        class LUCID_API {camel}Backward : public BinaryOp<{camel}Backward> {{
        public:
            static constexpr bool kSavesInputs = {saves_str};  // {'save' if saves else 'do not save'} inputs
            static const OpSchema schema_v1;

            static Storage dispatch(backend::IBackend& be,
                                    const Storage& a, const Storage& b,
                                    const Shape& shape, Dtype dt) {{
                return be.{name}(a, b, shape, dt);
            }}

            // TODO: implement.
            std::pair<Storage, Storage> grad_formula(const Storage& grad_out);

            // TODO: implement graph-mode gradient.
            std::pair<TensorImplPtr, TensorImplPtr> grad_formula_impl(
                const TensorImplPtr& grad_out,
                const TensorImplPtr& /*a*/,
                const TensorImplPtr& /*b*/) {{
                // Placeholder: pass grad through to both inputs.
                return {{grad_out, grad_out}};
            }}
        }};

        LUCID_API TensorImplPtr {name}_op(const TensorImplPtr& a, const TensorImplPtr& b);

        }}  // namespace lucid
        """)


def _binary_cpp(name: str, camel: str, amp: str) -> str:
    amp_e = amp_enum(amp)
    return dedent(f"""\
        // lucid/_C/ops/bfunc/{camel}.cpp
        //
        // Auto-generated by tools/new_op.py. Fill in the TODO sections.

        #include "{camel}.h"

        #include <utility>
        #include "../../core/OpRegistry.h"

        namespace lucid {{

        const OpSchema {camel}Backward::schema_v1{{"{name}", 1, AmpPolicy::{amp_e}, true}};

        // TODO: implement gradient.
        std::pair<Storage, Storage> {camel}Backward::grad_formula(const Storage& grad_out) {{
            (void)grad_out;
            throw std::runtime_error("{name} backward: not yet implemented");
        }}

        TensorImplPtr {name}_op(const TensorImplPtr& a, const TensorImplPtr& b) {{
            return {camel}Backward::forward(a, b);
        }}
        LUCID_REGISTER_OP({camel}Backward)

        }}  // namespace lucid
        """)


# ── COMPOSITE ─────────────────────────────────────────────────────────────────


def _composite_py(name: str) -> str:
    return dedent(f"""\
        # lucid/_ops/composite/{name}.py
        #
        # Auto-generated by tools/new_op.py  (kind=composite).
        # Implement {name} using existing Lucid primitives (no C++ needed).

        import lucid
        from lucid._tensor.tensor import Tensor


        def {name}(x: Tensor) -> Tensor:
            \"\"\"TODO: docstring.\"\"\"
            # TODO: implement using lucid.* primitives
            raise NotImplementedError("{name}: not yet implemented")
        """)


# ── file modifications ────────────────────────────────────────────────────────


def _mod_ibackend_unary(name: str, dry_run: bool) -> None:
    path = BE / "IBackend.h"
    text = read(path)
    anchor = "    virtual Storage erfinv(const Storage& a, const Shape& shape, Dtype dt) = 0;"
    insertion = (
        "\n    virtual Storage "
        f"{name}(const Storage& a, const Shape& shape, Dtype dt) = 0;"
        "  // new_op.py"
    )
    write(path, insert_after(text, anchor, insertion), dry_run)


def _mod_ibackend_binary(name: str, dry_run: bool) -> None:
    path = BE / "IBackend.h"
    text = read(path)
    # Binary ops live near "add" in IBackend
    anchor = "    virtual Storage add(const Storage& a, const Storage& b, const Shape& shape, Dtype dt) = 0;"
    insertion = (
        "\n    virtual Storage "
        f"{name}(const Storage& a, const Storage& b, const Shape& shape, Dtype dt) = 0;"
        "  // new_op.py"
    )
    write(path, insert_after(text, anchor, insertion), dry_run)


def _mod_cpu_unary(name: str, dry_run: bool) -> None:
    path = BE / "cpu" / "CpuBackend.h"
    text = read(path)
    # Insert before the reciprocal implementation (comes right after erfinv)
    anchor = "    Storage reciprocal(const Storage& a, const Shape& shape, Dtype dt) override {"
    stub = (
        f"    // TODO: implement {name} on CPU (vDSP/vForce/Accelerate).\n"
        f"    Storage {name}(const Storage& a, const Shape& shape, Dtype dt) override {{\n"
        f"        (void)a; (void)shape; (void)dt;\n"
        f'        ErrorBuilder("cpu_backend::{name}").not_implemented("fill in implementation");\n'
        f"        return a;\n"
        f"    }}\n\n"
    )
    write(path, insert_before(text, anchor, stub), dry_run)


def _mod_cpu_binary(name: str, dry_run: bool) -> None:
    path = BE / "cpu" / "CpuBackend.h"
    text = read(path)
    anchor = "    Storage add(const Storage& a, const Storage& b, const Shape& shape, Dtype dt) override {"
    stub = (
        f"    // TODO: implement {name} on CPU.\n"
        f"    Storage {name}(const Storage& a, const Storage& b,\n"
        f"                   const Shape& shape, Dtype dt) override {{\n"
        f"        (void)a; (void)b; (void)shape; (void)dt;\n"
        f'        ErrorBuilder("cpu_backend::{name}").not_implemented("fill in implementation");\n'
        f"        return a;\n"
        f"    }}\n\n"
    )
    write(path, insert_before(text, anchor, stub), dry_run)


def _mod_gpu_unary(name: str, dry_run: bool) -> None:
    path = BE / "gpu" / "GpuBackend.h"
    text = read(path)
    anchor = "    Storage erfinv(const Storage& a, const Shape& shape, Dtype dt) override {\n        return mlx_unary(a, shape, dt, [](auto& x) { return ::mlx::core::erfinv(x); });\n    }"
    stub = (
        f"\n\n"
        f"    // TODO: replace with the correct MLX op for {name}.\n"
        f"    Storage {name}(const Storage& a, const Shape& shape, Dtype dt) override {{\n"
        f"        return mlx_unary(a, shape, dt, [dt](auto& x) {{\n"
        f"            // TODO: return ::mlx::core::{name}(x);\n"
        f"            (void)dt;\n"
        f'            throw std::runtime_error("{name}: GPU kernel not yet implemented");\n'
        f"            return x;\n"
        f"        }});\n"
        f"    }}"
    )
    write(path, insert_after(text, anchor, stub), dry_run)


def _mod_gpu_binary(name: str, dry_run: bool) -> None:
    path = BE / "gpu" / "GpuBackend.h"
    text = read(path)
    anchor = "    Storage add(const Storage& a, const Storage& b, const Shape& shape, Dtype dt) override {"
    stub = (
        f"    // TODO: replace with the correct MLX op for {name}.\n"
        f"    Storage {name}(const Storage& a, const Storage& b,\n"
        f"                   const Shape& shape, Dtype dt) override {{\n"
        f"        return mlx_binary(a, b, shape, dt, [](auto& x, auto& y) {{\n"
        f"            // TODO: return ::mlx::core::{name}(x, y);\n"
        f'            throw std::runtime_error("{name}: GPU kernel not yet implemented");\n'
        f"            return x;\n"
        f"        }});\n"
        f"    }}\n\n"
    )
    write(path, insert_before(text, anchor, stub), dry_run)


def _mod_bind_unary(name: str, camel: str, dry_run: bool) -> None:
    path = BIND / "bind_ufunc.cpp"
    text = read(path)
    # Add include
    anchor_inc = '#include "../ops/ufunc/Exponential.h"'
    inc_line = f'\n#include "../ops/ufunc/{camel}.h"'
    text = insert_after(text, anchor_inc, inc_line)
    # Add bind call
    anchor_bind = "    bind_unary<ErfinvBackward>(m, &erfinv_op);"
    bind_line = f"\n    bind_unary<{camel}Backward>(m, &{name}_op);"
    text = insert_after(text, anchor_bind, bind_line)
    write(path, text, dry_run)


def _mod_bind_binary(name: str, camel: str, dry_run: bool) -> None:
    path = BIND / "bind_bfunc.cpp"
    text = read(path)
    # Find last bind_binary call and insert after
    last_bind = text.rfind("bind_binary<")
    if last_bind == -1:
        raise ValueError("bind_binary not found in bind_bfunc.cpp")
    eol = text.find("\n", last_bind)
    insertion = f"\n    bind_binary<{camel}Backward>(m, &{name}_op);"
    text = text[:eol] + insertion + text[eol:]
    # Add include near Add.h
    anchor_inc = '#include "../ops/bfunc/Add.h"'
    inc_line = f'\n#include "../ops/bfunc/{camel}.h"'
    text = insert_after(text, anchor_inc, inc_line)
    write(path, text, dry_run)


def _mod_cmake(name: str, camel: str, kind: str, dry_run: bool) -> None:
    text = read(CMAKE)
    subdir = "ufunc" if kind == "unary" else "bfunc"
    # Find the last ops/{subdir}/*.cpp line
    pattern = re.compile(rf"    ops/{subdir}/\S+\.cpp")
    matches = list(pattern.finditer(text))
    if not matches:
        raise ValueError(f"No ops/{subdir}/*.cpp entries found in CMakeLists.txt")
    last = matches[-1]
    end = last.end()
    insertion = f"\n    ops/{subdir}/{camel}.cpp"
    text = text[:end] + insertion + text[end:]
    write(CMAKE, text, dry_run)


def _mod_init_py(name: str, export: bool, dry_run: bool) -> None:
    text = read(INIT)
    anchor_ops = '    "erf", "erfinv",'
    insertion_ops = f'\n    "{name}",'
    text = insert_after(text, anchor_ops, insertion_ops)
    if export:
        # Also add to __all__ unary section
        anchor_all = '    "relu", "sigmoid",'
        insertion_all = f'\n    "{name}",'
        text = insert_after(text, anchor_all, insertion_all)
    write(INIT, text, dry_run)


def _mod_registry(name: str, dry_run: bool) -> None:
    """Add an OpEntry for a simple unary/binary op to _ops/_registry.py."""
    text = read(REGISTRY)
    # Insert after the erfinv OpEntry line
    anchor = '    OpEntry("erfinv", _R.erfinv, 1, method_name="erfinv", free_fn_name="erfinv"),'
    insertion = (
        f'\n    OpEntry("{name}", _R.{name}, 1,'
        f' method_name="{name}", free_fn_name="{name}"),'
    )
    write(REGISTRY, insert_after(text, anchor, insertion), dry_run)


def _mod_composite_init(name: str, dry_run: bool) -> None:
    composite_dir = ROOT / "lucid" / "_ops" / "composite"
    init_path = composite_dir / "__init__.py"
    if not init_path.exists():
        print(
            f"  ⚠️  {init_path.relative_to(ROOT)} not found — skip composite __init__ update"
        )
        return
    text = read(init_path)
    # Append import at end
    line = f"\nfrom lucid._ops.composite.{name} import {name}  # noqa: F401"
    if name not in text:
        text = text + line
    write(init_path, text, dry_run)


# ── main ──────────────────────────────────────────────────────────────────────


def run(args: argparse.Namespace) -> None:
    name = args.name
    camel = to_camel(name)
    kind = args.kind
    dry = args.dry_run

    print(f"\n{'═'*60}")
    print(f"  new_op.py  |  name={name}  kind={kind}  camel={camel}")
    print(f"{'═'*60}\n")

    if kind == "unary":
        si = args.save_input
        so = args.save_output
        amp = args.amp

        # 1. New header
        h_path = OPS / "ufunc" / f"{camel}.h"
        if h_path.exists() and not dry:
            print(f"  ⚠️   {h_path.relative_to(ROOT)} already exists — skipping")
        else:
            write(h_path, _unary_header(name, camel, amp, si, so), dry)

        # 2. New cpp
        cpp_path = OPS / "ufunc" / f"{camel}.cpp"
        if cpp_path.exists() and not dry:
            print(f"  ⚠️   {cpp_path.relative_to(ROOT)} already exists — skipping")
        else:
            write(cpp_path, _unary_cpp(name, camel, amp, si, so), dry)

        # 3. IBackend.h
        _mod_ibackend_unary(name, dry)

        # 4. CpuBackend.h
        _mod_cpu_unary(name, dry)

        # 5. GpuBackend.h
        _mod_gpu_unary(name, dry)

        # 6. bind_ufunc.cpp
        _mod_bind_unary(name, camel, dry)

        # 7. CMakeLists.txt
        _mod_cmake(name, camel, kind, dry)

        # 8. lucid/__init__.py
        _mod_init_py(name, args.export, dry)

        # 9. _ops/_registry.py
        _mod_registry(name, dry)

    elif kind == "binary":
        amp = args.amp
        saves = args.save_input

        h_path = OPS / "bfunc" / f"{camel}.h"
        if h_path.exists() and not dry:
            print(f"  ⚠️   {h_path.relative_to(ROOT)} already exists — skipping")
        else:
            write(h_path, _binary_header(name, camel, amp, saves), dry)

        cpp_path = OPS / "bfunc" / f"{camel}.cpp"
        if cpp_path.exists() and not dry:
            print(f"  ⚠️   {cpp_path.relative_to(ROOT)} already exists — skipping")
        else:
            write(cpp_path, _binary_cpp(name, camel, amp), dry)

        _mod_ibackend_binary(name, dry)
        _mod_cpu_binary(name, dry)
        _mod_gpu_binary(name, dry)
        _mod_bind_binary(name, camel, dry)
        _mod_cmake(name, camel, kind, dry)
        _mod_init_py(name, args.export, dry)
        _mod_registry(name, dry)

    elif kind == "composite":
        composite_dir = ROOT / "lucid" / "_ops" / "composite"
        composite_dir.mkdir(parents=True, exist_ok=True)

        py_path = composite_dir / f"{name}.py"
        if py_path.exists() and not dry:
            print(f"  ⚠️   {py_path.relative_to(ROOT)} already exists — skipping")
        else:
            write(py_path, _composite_py(name), dry)

        _mod_composite_init(name, dry)
        # Add to _OPS_NAMES so lucid.name works
        _mod_init_py(name, args.export, dry)

    if not dry:
        print("\n  🔧  Regenerating stubs (gen_pyi.py)...")
        result = subprocess.run(
            [sys.executable, str(ROOT / "tools" / "gen_pyi.py")],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            print("  ✅  Stubs regenerated")
        else:
            print(f"  ⚠️   gen_pyi.py failed:\n{result.stderr}")

        print(f"""
{'─'*60}
Next steps:
  1. Fill in gradient formula in:
       lucid/_C/ops/ufunc/{camel}.cpp  (grad_formula + grad_formula_impl)
  2. Add CPU kernel:
       lucid/_C/backend/cpu/CpuBackend.h  (replace NotImplementedError stub)
  3. Add GPU kernel:
       lucid/_C/backend/gpu/GpuBackend.h  (replace throw stub with MLX op)
  4. Build:
       cmake --build build/temp.macosx-*/lucid__C_engine/ -j$(sysctl -n hw.ncpu)
       cp build/lib.*/lucid/_C/engine.cpython-*.so lucid/_C/
  5. Write tests + parity test.
{'─'*60}
""")
    else:
        print("\n  (dry-run — no files modified)")


def main() -> None:
    p = argparse.ArgumentParser(
        description="Lucid op scaffolding — generates boilerplate for a new engine op.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("name", help="snake_case op name (e.g. softclamp)")
    p.add_argument(
        "--kind",
        choices=["unary", "binary", "composite"],
        default="unary",
        help="op kind (default: unary)",
    )
    p.add_argument(
        "--save-input",
        action="store_true",
        help="save forward inputs for backward (unary/binary)",
    )
    p.add_argument(
        "--save-output",
        action="store_true",
        help="save forward output for backward (unary only)",
    )
    p.add_argument(
        "--amp",
        choices=["keep", "promote", "fp32"],
        default="promote",
        help="AMP dtype policy (default: promote)",
    )
    p.add_argument(
        "--export",
        action="store_true",
        help="also add to lucid.__all__ (default: _OPS_NAMES only)",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="print what would change without modifying files",
    )
    args = p.parse_args()

    # Validate name
    if not re.match(r"^[a-z][a-z0-9_]*$", args.name):
        p.error(f"name must be snake_case lowercase: {args.name!r}")

    # Check for existing op
    camel = to_camel(args.name)
    if args.kind == "unary":
        target = OPS / "ufunc" / f"{camel}.h"
    elif args.kind == "binary":
        target = OPS / "bfunc" / f"{camel}.h"
    else:
        target = ROOT / "lucid" / "_ops" / "composite" / f"{args.name}.py"

    if target.exists() and not args.dry_run:
        print(f"⚠️  Op already exists: {target.relative_to(ROOT)}")
        print("   Add --dry-run to preview, or delete the existing file first.")
        sys.exit(1)

    try:
        run(args)
    except ValueError as e:
        print(f"\n❌  {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
